// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/microsoft/azure-devops-go-api/azuredevops/v7/pipelinepermissions (interfaces: Client)
//
// Generated by this command:
//
//	mockgen -package=mocks -destination internal/mocks/pipelinepermissions_client_mock.go -mock_names Client=MockPipelinePermissionsClient github.com/microsoft/azure-devops-go-api/azuredevops/v7/pipelinepermissions Client
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	pipelinepermissions "github.com/microsoft/azure-devops-go-api/azuredevops/v7/pipelinepermissions"
	gomock "go.uber.org/mock/gomock"
)

// MockPipelinePermissionsClient is a mock of Client interface.
type MockPipelinePermissionsClient struct {
	ctrl     *gomock.Controller
	recorder *MockPipelinePermissionsClientMockRecorder
	isgomock struct{}
}

// MockPipelinePermissionsClientMockRecorder is the mock recorder for MockPipelinePermissionsClient.
type MockPipelinePermissionsClientMockRecorder struct {
	mock *MockPipelinePermissionsClient
}

// NewMockPipelinePermissionsClient creates a new mock instance.
func NewMockPipelinePermissionsClient(ctrl *gomock.Controller) *MockPipelinePermissionsClient {
	mock := &MockPipelinePermissionsClient{ctrl: ctrl}
	mock.recorder = &MockPipelinePermissionsClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPipelinePermissionsClient) EXPECT() *MockPipelinePermissionsClientMockRecorder {
	return m.recorder
}

// GetPipelinePermissionsForResource mocks base method.
func (m *MockPipelinePermissionsClient) GetPipelinePermissionsForResource(arg0 context.Context, arg1 pipelinepermissions.GetPipelinePermissionsForResourceArgs) (*pipelinepermissions.ResourcePipelinePermissions, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPipelinePermissionsForResource", arg0, arg1)
	ret0, _ := ret[0].(*pipelinepermissions.ResourcePipelinePermissions)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPipelinePermissionsForResource indicates an expected call of GetPipelinePermissionsForResource.
func (mr *MockPipelinePermissionsClientMockRecorder) GetPipelinePermissionsForResource(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPipelinePermissionsForResource", reflect.TypeOf((*MockPipelinePermissionsClient)(nil).GetPipelinePermissionsForResource), arg0, arg1)
}

// UpdatePipelinePermisionsForResource mocks base method.
func (m *MockPipelinePermissionsClient) UpdatePipelinePermisionsForResource(arg0 context.Context, arg1 pipelinepermissions.UpdatePipelinePermisionsForResourceArgs) (*pipelinepermissions.ResourcePipelinePermissions, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdatePipelinePermisionsForResource", arg0, arg1)
	ret0, _ := ret[0].(*pipelinepermissions.ResourcePipelinePermissions)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdatePipelinePermisionsForResource indicates an expected call of UpdatePipelinePermisionsForResource.
func (mr *MockPipelinePermissionsClientMockRecorder) UpdatePipelinePermisionsForResource(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdatePipelinePermisionsForResource", reflect.TypeOf((*MockPipelinePermissionsClient)(nil).UpdatePipelinePermisionsForResource), arg0, arg1)
}

// UpdatePipelinePermisionsForResources mocks base method.
func (m *MockPipelinePermissionsClient) UpdatePipelinePermisionsForResources(arg0 context.Context, arg1 pipelinepermissions.UpdatePipelinePermisionsForResourcesArgs) (*[]pipelinepermissions.ResourcePipelinePermissions, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdatePipelinePermisionsForResources", arg0, arg1)
	ret0, _ := ret[0].(*[]pipelinepermissions.ResourcePipelinePermissions)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdatePipelinePermisionsForResources indicates an expected call of UpdatePipelinePermisionsForResources.
func (mr *MockPipelinePermissionsClientMockRecorder) UpdatePipelinePermisionsForResources(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdatePipelinePermisionsForResources", reflect.TypeOf((*MockPipelinePermissionsClient)(nil).UpdatePipelinePermisionsForResources), arg0, arg1)
}
