// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/microsoft/azure-devops-go-api/azuredevops/v7/serviceendpoint (interfaces: Client)
//
// Generated by this command:
//
//	mockgen -package=mocks -destination internal/mocks/serviceendpoint_client_mock.go -mock_names Client=MockServiceEndpointClient github.com/microsoft/azure-devops-go-api/azuredevops/v7/serviceendpoint Client
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	serviceendpoint "github.com/microsoft/azure-devops-go-api/azuredevops/v7/serviceendpoint"
	gomock "go.uber.org/mock/gomock"
)

// MockServiceEndpointClient is a mock of Client interface.
type MockServiceEndpointClient struct {
	ctrl     *gomock.Controller
	recorder *MockServiceEndpointClientMockRecorder
	isgomock struct{}
}

// MockServiceEndpointClientMockRecorder is the mock recorder for MockServiceEndpointClient.
type MockServiceEndpointClientMockRecorder struct {
	mock *MockServiceEndpointClient
}

// NewMockServiceEndpointClient creates a new mock instance.
func NewMockServiceEndpointClient(ctrl *gomock.Controller) *MockServiceEndpointClient {
	mock := &MockServiceEndpointClient{ctrl: ctrl}
	mock.recorder = &MockServiceEndpointClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockServiceEndpointClient) EXPECT() *MockServiceEndpointClientMockRecorder {
	return m.recorder
}

// CreateServiceEndpoint mocks base method.
func (m *MockServiceEndpointClient) CreateServiceEndpoint(arg0 context.Context, arg1 serviceendpoint.CreateServiceEndpointArgs) (*serviceendpoint.ServiceEndpoint, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateServiceEndpoint", arg0, arg1)
	ret0, _ := ret[0].(*serviceendpoint.ServiceEndpoint)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateServiceEndpoint indicates an expected call of CreateServiceEndpoint.
func (mr *MockServiceEndpointClientMockRecorder) CreateServiceEndpoint(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateServiceEndpoint", reflect.TypeOf((*MockServiceEndpointClient)(nil).CreateServiceEndpoint), arg0, arg1)
}

// DeleteServiceEndpoint mocks base method.
func (m *MockServiceEndpointClient) DeleteServiceEndpoint(arg0 context.Context, arg1 serviceendpoint.DeleteServiceEndpointArgs) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteServiceEndpoint", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteServiceEndpoint indicates an expected call of DeleteServiceEndpoint.
func (mr *MockServiceEndpointClientMockRecorder) DeleteServiceEndpoint(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteServiceEndpoint", reflect.TypeOf((*MockServiceEndpointClient)(nil).DeleteServiceEndpoint), arg0, arg1)
}

// ExecuteServiceEndpointRequest mocks base method.
func (m *MockServiceEndpointClient) ExecuteServiceEndpointRequest(arg0 context.Context, arg1 serviceendpoint.ExecuteServiceEndpointRequestArgs) (*serviceendpoint.ServiceEndpointRequestResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExecuteServiceEndpointRequest", arg0, arg1)
	ret0, _ := ret[0].(*serviceendpoint.ServiceEndpointRequestResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExecuteServiceEndpointRequest indicates an expected call of ExecuteServiceEndpointRequest.
func (mr *MockServiceEndpointClientMockRecorder) ExecuteServiceEndpointRequest(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExecuteServiceEndpointRequest", reflect.TypeOf((*MockServiceEndpointClient)(nil).ExecuteServiceEndpointRequest), arg0, arg1)
}

// GetServiceEndpointDetails mocks base method.
func (m *MockServiceEndpointClient) GetServiceEndpointDetails(arg0 context.Context, arg1 serviceendpoint.GetServiceEndpointDetailsArgs) (*serviceendpoint.ServiceEndpoint, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetServiceEndpointDetails", arg0, arg1)
	ret0, _ := ret[0].(*serviceendpoint.ServiceEndpoint)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetServiceEndpointDetails indicates an expected call of GetServiceEndpointDetails.
func (mr *MockServiceEndpointClientMockRecorder) GetServiceEndpointDetails(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetServiceEndpointDetails", reflect.TypeOf((*MockServiceEndpointClient)(nil).GetServiceEndpointDetails), arg0, arg1)
}

// GetServiceEndpointExecutionRecords mocks base method.
func (m *MockServiceEndpointClient) GetServiceEndpointExecutionRecords(arg0 context.Context, arg1 serviceendpoint.GetServiceEndpointExecutionRecordsArgs) (*serviceendpoint.GetServiceEndpointExecutionRecordsResponseValue, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetServiceEndpointExecutionRecords", arg0, arg1)
	ret0, _ := ret[0].(*serviceendpoint.GetServiceEndpointExecutionRecordsResponseValue)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetServiceEndpointExecutionRecords indicates an expected call of GetServiceEndpointExecutionRecords.
func (mr *MockServiceEndpointClientMockRecorder) GetServiceEndpointExecutionRecords(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetServiceEndpointExecutionRecords", reflect.TypeOf((*MockServiceEndpointClient)(nil).GetServiceEndpointExecutionRecords), arg0, arg1)
}

// GetServiceEndpointTypes mocks base method.
func (m *MockServiceEndpointClient) GetServiceEndpointTypes(arg0 context.Context, arg1 serviceendpoint.GetServiceEndpointTypesArgs) (*[]serviceendpoint.ServiceEndpointType, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetServiceEndpointTypes", arg0, arg1)
	ret0, _ := ret[0].(*[]serviceendpoint.ServiceEndpointType)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetServiceEndpointTypes indicates an expected call of GetServiceEndpointTypes.
func (mr *MockServiceEndpointClientMockRecorder) GetServiceEndpointTypes(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetServiceEndpointTypes", reflect.TypeOf((*MockServiceEndpointClient)(nil).GetServiceEndpointTypes), arg0, arg1)
}

// GetServiceEndpoints mocks base method.
func (m *MockServiceEndpointClient) GetServiceEndpoints(arg0 context.Context, arg1 serviceendpoint.GetServiceEndpointsArgs) (*[]serviceendpoint.ServiceEndpoint, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetServiceEndpoints", arg0, arg1)
	ret0, _ := ret[0].(*[]serviceendpoint.ServiceEndpoint)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetServiceEndpoints indicates an expected call of GetServiceEndpoints.
func (mr *MockServiceEndpointClientMockRecorder) GetServiceEndpoints(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetServiceEndpoints", reflect.TypeOf((*MockServiceEndpointClient)(nil).GetServiceEndpoints), arg0, arg1)
}

// GetServiceEndpointsByNames mocks base method.
func (m *MockServiceEndpointClient) GetServiceEndpointsByNames(arg0 context.Context, arg1 serviceendpoint.GetServiceEndpointsByNamesArgs) (*[]serviceendpoint.ServiceEndpoint, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetServiceEndpointsByNames", arg0, arg1)
	ret0, _ := ret[0].(*[]serviceendpoint.ServiceEndpoint)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetServiceEndpointsByNames indicates an expected call of GetServiceEndpointsByNames.
func (mr *MockServiceEndpointClientMockRecorder) GetServiceEndpointsByNames(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetServiceEndpointsByNames", reflect.TypeOf((*MockServiceEndpointClient)(nil).GetServiceEndpointsByNames), arg0, arg1)
}

// GetServiceEndpointsWithRefreshedAuthentication mocks base method.
func (m *MockServiceEndpointClient) GetServiceEndpointsWithRefreshedAuthentication(arg0 context.Context, arg1 serviceendpoint.GetServiceEndpointsWithRefreshedAuthenticationArgs) (*[]serviceendpoint.ServiceEndpoint, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetServiceEndpointsWithRefreshedAuthentication", arg0, arg1)
	ret0, _ := ret[0].(*[]serviceendpoint.ServiceEndpoint)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetServiceEndpointsWithRefreshedAuthentication indicates an expected call of GetServiceEndpointsWithRefreshedAuthentication.
func (mr *MockServiceEndpointClientMockRecorder) GetServiceEndpointsWithRefreshedAuthentication(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetServiceEndpointsWithRefreshedAuthentication", reflect.TypeOf((*MockServiceEndpointClient)(nil).GetServiceEndpointsWithRefreshedAuthentication), arg0, arg1)
}

// ShareServiceEndpoint mocks base method.
func (m *MockServiceEndpointClient) ShareServiceEndpoint(arg0 context.Context, arg1 serviceendpoint.ShareServiceEndpointArgs) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ShareServiceEndpoint", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// ShareServiceEndpoint indicates an expected call of ShareServiceEndpoint.
func (mr *MockServiceEndpointClientMockRecorder) ShareServiceEndpoint(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ShareServiceEndpoint", reflect.TypeOf((*MockServiceEndpointClient)(nil).ShareServiceEndpoint), arg0, arg1)
}

// UpdateServiceEndpoint mocks base method.
func (m *MockServiceEndpointClient) UpdateServiceEndpoint(arg0 context.Context, arg1 serviceendpoint.UpdateServiceEndpointArgs) (*serviceendpoint.ServiceEndpoint, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateServiceEndpoint", arg0, arg1)
	ret0, _ := ret[0].(*serviceendpoint.ServiceEndpoint)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateServiceEndpoint indicates an expected call of UpdateServiceEndpoint.
func (mr *MockServiceEndpointClientMockRecorder) UpdateServiceEndpoint(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateServiceEndpoint", reflect.TypeOf((*MockServiceEndpointClient)(nil).UpdateServiceEndpoint), arg0, arg1)
}

// UpdateServiceEndpoints mocks base method.
func (m *MockServiceEndpointClient) UpdateServiceEndpoints(arg0 context.Context, arg1 serviceendpoint.UpdateServiceEndpointsArgs) (*[]serviceendpoint.ServiceEndpoint, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateServiceEndpoints", arg0, arg1)
	ret0, _ := ret[0].(*[]serviceendpoint.ServiceEndpoint)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateServiceEndpoints indicates an expected call of UpdateServiceEndpoints.
func (mr *MockServiceEndpointClientMockRecorder) UpdateServiceEndpoints(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateServiceEndpoints", reflect.TypeOf((*MockServiceEndpointClient)(nil).UpdateServiceEndpoints), arg0, arg1)
}
