// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/microsoft/azure-devops-go-api/azuredevops/v7/taskagent (interfaces: Client)
//
// Generated by this command:
//
//	mockgen -package=mocks -destination internal/mocks/taskagent_client_mock.go -mock_names Client=MockTaskAgentClient github.com/microsoft/azure-devops-go-api/azuredevops/v7/taskagent Client
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	taskagent "github.com/microsoft/azure-devops-go-api/azuredevops/v7/taskagent"
	gomock "go.uber.org/mock/gomock"
)

// MockTaskAgentClient is a mock of Client interface.
type MockTaskAgentClient struct {
	ctrl     *gomock.Controller
	recorder *MockTaskAgentClientMockRecorder
	isgomock struct{}
}

// MockTaskAgentClientMockRecorder is the mock recorder for MockTaskAgentClient.
type MockTaskAgentClientMockRecorder struct {
	mock *MockTaskAgentClient
}

// NewMockTaskAgentClient creates a new mock instance.
func NewMockTaskAgentClient(ctrl *gomock.Controller) *MockTaskAgentClient {
	mock := &MockTaskAgentClient{ctrl: ctrl}
	mock.recorder = &MockTaskAgentClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTaskAgentClient) EXPECT() *MockTaskAgentClientMockRecorder {
	return m.recorder
}

// AddAgent mocks base method.
func (m *MockTaskAgentClient) AddAgent(arg0 context.Context, arg1 taskagent.AddAgentArgs) (*taskagent.TaskAgent, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddAgent", arg0, arg1)
	ret0, _ := ret[0].(*taskagent.TaskAgent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddAgent indicates an expected call of AddAgent.
func (mr *MockTaskAgentClientMockRecorder) AddAgent(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddAgent", reflect.TypeOf((*MockTaskAgentClient)(nil).AddAgent), arg0, arg1)
}

// AddAgentCloud mocks base method.
func (m *MockTaskAgentClient) AddAgentCloud(arg0 context.Context, arg1 taskagent.AddAgentCloudArgs) (*taskagent.TaskAgentCloud, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddAgentCloud", arg0, arg1)
	ret0, _ := ret[0].(*taskagent.TaskAgentCloud)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddAgentCloud indicates an expected call of AddAgentCloud.
func (mr *MockTaskAgentClientMockRecorder) AddAgentCloud(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddAgentCloud", reflect.TypeOf((*MockTaskAgentClient)(nil).AddAgentCloud), arg0, arg1)
}

// AddAgentPool mocks base method.
func (m *MockTaskAgentClient) AddAgentPool(arg0 context.Context, arg1 taskagent.AddAgentPoolArgs) (*taskagent.TaskAgentPool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddAgentPool", arg0, arg1)
	ret0, _ := ret[0].(*taskagent.TaskAgentPool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddAgentPool indicates an expected call of AddAgentPool.
func (mr *MockTaskAgentClientMockRecorder) AddAgentPool(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddAgentPool", reflect.TypeOf((*MockTaskAgentClient)(nil).AddAgentPool), arg0, arg1)
}

// AddAgentQueue mocks base method.
func (m *MockTaskAgentClient) AddAgentQueue(arg0 context.Context, arg1 taskagent.AddAgentQueueArgs) (*taskagent.TaskAgentQueue, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddAgentQueue", arg0, arg1)
	ret0, _ := ret[0].(*taskagent.TaskAgentQueue)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddAgentQueue indicates an expected call of AddAgentQueue.
func (mr *MockTaskAgentClientMockRecorder) AddAgentQueue(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddAgentQueue", reflect.TypeOf((*MockTaskAgentClient)(nil).AddAgentQueue), arg0, arg1)
}

// AddDeploymentGroup mocks base method.
func (m *MockTaskAgentClient) AddDeploymentGroup(arg0 context.Context, arg1 taskagent.AddDeploymentGroupArgs) (*taskagent.DeploymentGroup, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddDeploymentGroup", arg0, arg1)
	ret0, _ := ret[0].(*taskagent.DeploymentGroup)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddDeploymentGroup indicates an expected call of AddDeploymentGroup.
func (mr *MockTaskAgentClientMockRecorder) AddDeploymentGroup(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddDeploymentGroup", reflect.TypeOf((*MockTaskAgentClient)(nil).AddDeploymentGroup), arg0, arg1)
}

// AddEnvironment mocks base method.
func (m *MockTaskAgentClient) AddEnvironment(arg0 context.Context, arg1 taskagent.AddEnvironmentArgs) (*taskagent.EnvironmentInstance, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddEnvironment", arg0, arg1)
	ret0, _ := ret[0].(*taskagent.EnvironmentInstance)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddEnvironment indicates an expected call of AddEnvironment.
func (mr *MockTaskAgentClientMockRecorder) AddEnvironment(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddEnvironment", reflect.TypeOf((*MockTaskAgentClient)(nil).AddEnvironment), arg0, arg1)
}

// AddKubernetesResourcExistingEndpoint mocks base method.
func (m *MockTaskAgentClient) AddKubernetesResourcExistingEndpoint(ctx context.Context, args taskagent.AddKubernetesResourceArgsExistingEndpoint) (*taskagent.KubernetesResource, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddKubernetesResourcExistingEndpoint", ctx, args)
	ret0, _ := ret[0].(*taskagent.KubernetesResource)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddKubernetesResourcExistingEndpoint indicates an expected call of AddKubernetesResourcExistingEndpoint.
func (mr *MockTaskAgentClientMockRecorder) AddKubernetesResourcExistingEndpoint(ctx, args any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddKubernetesResourcExistingEndpoint", reflect.TypeOf((*MockTaskAgentClient)(nil).AddKubernetesResourcExistingEndpoint), ctx, args)
}

// AddKubernetesResourceNewEndpoint mocks base method.
func (m *MockTaskAgentClient) AddKubernetesResourceNewEndpoint(ctx context.Context, args taskagent.AddKubernetesResourceArgsNewEndpoint) (*taskagent.KubernetesResource, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddKubernetesResourceNewEndpoint", ctx, args)
	ret0, _ := ret[0].(*taskagent.KubernetesResource)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddKubernetesResourceNewEndpoint indicates an expected call of AddKubernetesResourceNewEndpoint.
func (mr *MockTaskAgentClientMockRecorder) AddKubernetesResourceNewEndpoint(ctx, args any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddKubernetesResourceNewEndpoint", reflect.TypeOf((*MockTaskAgentClient)(nil).AddKubernetesResourceNewEndpoint), ctx, args)
}

// AddTaskGroup mocks base method.
func (m *MockTaskAgentClient) AddTaskGroup(arg0 context.Context, arg1 taskagent.AddTaskGroupArgs) (*taskagent.TaskGroup, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddTaskGroup", arg0, arg1)
	ret0, _ := ret[0].(*taskagent.TaskGroup)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddTaskGroup indicates an expected call of AddTaskGroup.
func (mr *MockTaskAgentClientMockRecorder) AddTaskGroup(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddTaskGroup", reflect.TypeOf((*MockTaskAgentClient)(nil).AddTaskGroup), arg0, arg1)
}

// AddVariableGroup mocks base method.
func (m *MockTaskAgentClient) AddVariableGroup(arg0 context.Context, arg1 taskagent.AddVariableGroupArgs) (*taskagent.VariableGroup, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddVariableGroup", arg0, arg1)
	ret0, _ := ret[0].(*taskagent.VariableGroup)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddVariableGroup indicates an expected call of AddVariableGroup.
func (mr *MockTaskAgentClientMockRecorder) AddVariableGroup(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddVariableGroup", reflect.TypeOf((*MockTaskAgentClient)(nil).AddVariableGroup), arg0, arg1)
}

// DeleteAgent mocks base method.
func (m *MockTaskAgentClient) DeleteAgent(arg0 context.Context, arg1 taskagent.DeleteAgentArgs) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteAgent", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteAgent indicates an expected call of DeleteAgent.
func (mr *MockTaskAgentClientMockRecorder) DeleteAgent(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteAgent", reflect.TypeOf((*MockTaskAgentClient)(nil).DeleteAgent), arg0, arg1)
}

// DeleteAgentCloud mocks base method.
func (m *MockTaskAgentClient) DeleteAgentCloud(arg0 context.Context, arg1 taskagent.DeleteAgentCloudArgs) (*taskagent.TaskAgentCloud, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteAgentCloud", arg0, arg1)
	ret0, _ := ret[0].(*taskagent.TaskAgentCloud)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteAgentCloud indicates an expected call of DeleteAgentCloud.
func (mr *MockTaskAgentClientMockRecorder) DeleteAgentCloud(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteAgentCloud", reflect.TypeOf((*MockTaskAgentClient)(nil).DeleteAgentCloud), arg0, arg1)
}

// DeleteAgentPool mocks base method.
func (m *MockTaskAgentClient) DeleteAgentPool(arg0 context.Context, arg1 taskagent.DeleteAgentPoolArgs) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteAgentPool", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteAgentPool indicates an expected call of DeleteAgentPool.
func (mr *MockTaskAgentClientMockRecorder) DeleteAgentPool(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteAgentPool", reflect.TypeOf((*MockTaskAgentClient)(nil).DeleteAgentPool), arg0, arg1)
}

// DeleteAgentQueue mocks base method.
func (m *MockTaskAgentClient) DeleteAgentQueue(arg0 context.Context, arg1 taskagent.DeleteAgentQueueArgs) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteAgentQueue", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteAgentQueue indicates an expected call of DeleteAgentQueue.
func (mr *MockTaskAgentClientMockRecorder) DeleteAgentQueue(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteAgentQueue", reflect.TypeOf((*MockTaskAgentClient)(nil).DeleteAgentQueue), arg0, arg1)
}

// DeleteDeploymentGroup mocks base method.
func (m *MockTaskAgentClient) DeleteDeploymentGroup(arg0 context.Context, arg1 taskagent.DeleteDeploymentGroupArgs) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteDeploymentGroup", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteDeploymentGroup indicates an expected call of DeleteDeploymentGroup.
func (mr *MockTaskAgentClientMockRecorder) DeleteDeploymentGroup(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteDeploymentGroup", reflect.TypeOf((*MockTaskAgentClient)(nil).DeleteDeploymentGroup), arg0, arg1)
}

// DeleteDeploymentTarget mocks base method.
func (m *MockTaskAgentClient) DeleteDeploymentTarget(arg0 context.Context, arg1 taskagent.DeleteDeploymentTargetArgs) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteDeploymentTarget", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteDeploymentTarget indicates an expected call of DeleteDeploymentTarget.
func (mr *MockTaskAgentClientMockRecorder) DeleteDeploymentTarget(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteDeploymentTarget", reflect.TypeOf((*MockTaskAgentClient)(nil).DeleteDeploymentTarget), arg0, arg1)
}

// DeleteEnvironment mocks base method.
func (m *MockTaskAgentClient) DeleteEnvironment(arg0 context.Context, arg1 taskagent.DeleteEnvironmentArgs) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteEnvironment", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteEnvironment indicates an expected call of DeleteEnvironment.
func (mr *MockTaskAgentClientMockRecorder) DeleteEnvironment(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteEnvironment", reflect.TypeOf((*MockTaskAgentClient)(nil).DeleteEnvironment), arg0, arg1)
}

// DeleteKubernetesResource mocks base method.
func (m *MockTaskAgentClient) DeleteKubernetesResource(arg0 context.Context, arg1 taskagent.DeleteKubernetesResourceArgs) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteKubernetesResource", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteKubernetesResource indicates an expected call of DeleteKubernetesResource.
func (mr *MockTaskAgentClientMockRecorder) DeleteKubernetesResource(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteKubernetesResource", reflect.TypeOf((*MockTaskAgentClient)(nil).DeleteKubernetesResource), arg0, arg1)
}

// DeleteTaskGroup mocks base method.
func (m *MockTaskAgentClient) DeleteTaskGroup(arg0 context.Context, arg1 taskagent.DeleteTaskGroupArgs) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteTaskGroup", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteTaskGroup indicates an expected call of DeleteTaskGroup.
func (mr *MockTaskAgentClientMockRecorder) DeleteTaskGroup(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteTaskGroup", reflect.TypeOf((*MockTaskAgentClient)(nil).DeleteTaskGroup), arg0, arg1)
}

// DeleteVariableGroup mocks base method.
func (m *MockTaskAgentClient) DeleteVariableGroup(arg0 context.Context, arg1 taskagent.DeleteVariableGroupArgs) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteVariableGroup", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteVariableGroup indicates an expected call of DeleteVariableGroup.
func (mr *MockTaskAgentClientMockRecorder) DeleteVariableGroup(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteVariableGroup", reflect.TypeOf((*MockTaskAgentClient)(nil).DeleteVariableGroup), arg0, arg1)
}

// GetAgent mocks base method.
func (m *MockTaskAgentClient) GetAgent(arg0 context.Context, arg1 taskagent.GetAgentArgs) (*taskagent.TaskAgent, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAgent", arg0, arg1)
	ret0, _ := ret[0].(*taskagent.TaskAgent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAgent indicates an expected call of GetAgent.
func (mr *MockTaskAgentClientMockRecorder) GetAgent(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAgent", reflect.TypeOf((*MockTaskAgentClient)(nil).GetAgent), arg0, arg1)
}

// GetAgentCloud mocks base method.
func (m *MockTaskAgentClient) GetAgentCloud(arg0 context.Context, arg1 taskagent.GetAgentCloudArgs) (*taskagent.TaskAgentCloud, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAgentCloud", arg0, arg1)
	ret0, _ := ret[0].(*taskagent.TaskAgentCloud)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAgentCloud indicates an expected call of GetAgentCloud.
func (mr *MockTaskAgentClientMockRecorder) GetAgentCloud(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAgentCloud", reflect.TypeOf((*MockTaskAgentClient)(nil).GetAgentCloud), arg0, arg1)
}

// GetAgentCloudRequests mocks base method.
func (m *MockTaskAgentClient) GetAgentCloudRequests(arg0 context.Context, arg1 taskagent.GetAgentCloudRequestsArgs) (*[]taskagent.TaskAgentCloudRequest, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAgentCloudRequests", arg0, arg1)
	ret0, _ := ret[0].(*[]taskagent.TaskAgentCloudRequest)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAgentCloudRequests indicates an expected call of GetAgentCloudRequests.
func (mr *MockTaskAgentClientMockRecorder) GetAgentCloudRequests(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAgentCloudRequests", reflect.TypeOf((*MockTaskAgentClient)(nil).GetAgentCloudRequests), arg0, arg1)
}

// GetAgentCloudTypes mocks base method.
func (m *MockTaskAgentClient) GetAgentCloudTypes(arg0 context.Context, arg1 taskagent.GetAgentCloudTypesArgs) (*[]taskagent.TaskAgentCloudType, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAgentCloudTypes", arg0, arg1)
	ret0, _ := ret[0].(*[]taskagent.TaskAgentCloudType)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAgentCloudTypes indicates an expected call of GetAgentCloudTypes.
func (mr *MockTaskAgentClientMockRecorder) GetAgentCloudTypes(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAgentCloudTypes", reflect.TypeOf((*MockTaskAgentClient)(nil).GetAgentCloudTypes), arg0, arg1)
}

// GetAgentClouds mocks base method.
func (m *MockTaskAgentClient) GetAgentClouds(arg0 context.Context, arg1 taskagent.GetAgentCloudsArgs) (*[]taskagent.TaskAgentCloud, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAgentClouds", arg0, arg1)
	ret0, _ := ret[0].(*[]taskagent.TaskAgentCloud)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAgentClouds indicates an expected call of GetAgentClouds.
func (mr *MockTaskAgentClientMockRecorder) GetAgentClouds(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAgentClouds", reflect.TypeOf((*MockTaskAgentClient)(nil).GetAgentClouds), arg0, arg1)
}

// GetAgentPool mocks base method.
func (m *MockTaskAgentClient) GetAgentPool(arg0 context.Context, arg1 taskagent.GetAgentPoolArgs) (*taskagent.TaskAgentPool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAgentPool", arg0, arg1)
	ret0, _ := ret[0].(*taskagent.TaskAgentPool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAgentPool indicates an expected call of GetAgentPool.
func (mr *MockTaskAgentClientMockRecorder) GetAgentPool(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAgentPool", reflect.TypeOf((*MockTaskAgentClient)(nil).GetAgentPool), arg0, arg1)
}

// GetAgentPools mocks base method.
func (m *MockTaskAgentClient) GetAgentPools(arg0 context.Context, arg1 taskagent.GetAgentPoolsArgs) (*[]taskagent.TaskAgentPool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAgentPools", arg0, arg1)
	ret0, _ := ret[0].(*[]taskagent.TaskAgentPool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAgentPools indicates an expected call of GetAgentPools.
func (mr *MockTaskAgentClientMockRecorder) GetAgentPools(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAgentPools", reflect.TypeOf((*MockTaskAgentClient)(nil).GetAgentPools), arg0, arg1)
}

// GetAgentPoolsByIds mocks base method.
func (m *MockTaskAgentClient) GetAgentPoolsByIds(arg0 context.Context, arg1 taskagent.GetAgentPoolsByIdsArgs) (*[]taskagent.TaskAgentPool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAgentPoolsByIds", arg0, arg1)
	ret0, _ := ret[0].(*[]taskagent.TaskAgentPool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAgentPoolsByIds indicates an expected call of GetAgentPoolsByIds.
func (mr *MockTaskAgentClientMockRecorder) GetAgentPoolsByIds(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAgentPoolsByIds", reflect.TypeOf((*MockTaskAgentClient)(nil).GetAgentPoolsByIds), arg0, arg1)
}

// GetAgentQueue mocks base method.
func (m *MockTaskAgentClient) GetAgentQueue(arg0 context.Context, arg1 taskagent.GetAgentQueueArgs) (*taskagent.TaskAgentQueue, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAgentQueue", arg0, arg1)
	ret0, _ := ret[0].(*taskagent.TaskAgentQueue)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAgentQueue indicates an expected call of GetAgentQueue.
func (mr *MockTaskAgentClientMockRecorder) GetAgentQueue(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAgentQueue", reflect.TypeOf((*MockTaskAgentClient)(nil).GetAgentQueue), arg0, arg1)
}

// GetAgentQueues mocks base method.
func (m *MockTaskAgentClient) GetAgentQueues(arg0 context.Context, arg1 taskagent.GetAgentQueuesArgs) (*[]taskagent.TaskAgentQueue, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAgentQueues", arg0, arg1)
	ret0, _ := ret[0].(*[]taskagent.TaskAgentQueue)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAgentQueues indicates an expected call of GetAgentQueues.
func (mr *MockTaskAgentClientMockRecorder) GetAgentQueues(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAgentQueues", reflect.TypeOf((*MockTaskAgentClient)(nil).GetAgentQueues), arg0, arg1)
}

// GetAgentQueuesByIds mocks base method.
func (m *MockTaskAgentClient) GetAgentQueuesByIds(arg0 context.Context, arg1 taskagent.GetAgentQueuesByIdsArgs) (*[]taskagent.TaskAgentQueue, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAgentQueuesByIds", arg0, arg1)
	ret0, _ := ret[0].(*[]taskagent.TaskAgentQueue)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAgentQueuesByIds indicates an expected call of GetAgentQueuesByIds.
func (mr *MockTaskAgentClientMockRecorder) GetAgentQueuesByIds(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAgentQueuesByIds", reflect.TypeOf((*MockTaskAgentClient)(nil).GetAgentQueuesByIds), arg0, arg1)
}

// GetAgentQueuesByNames mocks base method.
func (m *MockTaskAgentClient) GetAgentQueuesByNames(arg0 context.Context, arg1 taskagent.GetAgentQueuesByNamesArgs) (*[]taskagent.TaskAgentQueue, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAgentQueuesByNames", arg0, arg1)
	ret0, _ := ret[0].(*[]taskagent.TaskAgentQueue)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAgentQueuesByNames indicates an expected call of GetAgentQueuesByNames.
func (mr *MockTaskAgentClientMockRecorder) GetAgentQueuesByNames(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAgentQueuesByNames", reflect.TypeOf((*MockTaskAgentClient)(nil).GetAgentQueuesByNames), arg0, arg1)
}

// GetAgentQueuesForPools mocks base method.
func (m *MockTaskAgentClient) GetAgentQueuesForPools(arg0 context.Context, arg1 taskagent.GetAgentQueuesForPoolsArgs) (*[]taskagent.TaskAgentQueue, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAgentQueuesForPools", arg0, arg1)
	ret0, _ := ret[0].(*[]taskagent.TaskAgentQueue)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAgentQueuesForPools indicates an expected call of GetAgentQueuesForPools.
func (mr *MockTaskAgentClientMockRecorder) GetAgentQueuesForPools(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAgentQueuesForPools", reflect.TypeOf((*MockTaskAgentClient)(nil).GetAgentQueuesForPools), arg0, arg1)
}

// GetAgents mocks base method.
func (m *MockTaskAgentClient) GetAgents(arg0 context.Context, arg1 taskagent.GetAgentsArgs) (*[]taskagent.TaskAgent, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAgents", arg0, arg1)
	ret0, _ := ret[0].(*[]taskagent.TaskAgent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAgents indicates an expected call of GetAgents.
func (mr *MockTaskAgentClientMockRecorder) GetAgents(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAgents", reflect.TypeOf((*MockTaskAgentClient)(nil).GetAgents), arg0, arg1)
}

// GetDeploymentGroup mocks base method.
func (m *MockTaskAgentClient) GetDeploymentGroup(arg0 context.Context, arg1 taskagent.GetDeploymentGroupArgs) (*taskagent.DeploymentGroup, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDeploymentGroup", arg0, arg1)
	ret0, _ := ret[0].(*taskagent.DeploymentGroup)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDeploymentGroup indicates an expected call of GetDeploymentGroup.
func (mr *MockTaskAgentClientMockRecorder) GetDeploymentGroup(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDeploymentGroup", reflect.TypeOf((*MockTaskAgentClient)(nil).GetDeploymentGroup), arg0, arg1)
}

// GetDeploymentGroups mocks base method.
func (m *MockTaskAgentClient) GetDeploymentGroups(arg0 context.Context, arg1 taskagent.GetDeploymentGroupsArgs) (*taskagent.GetDeploymentGroupsResponseValue, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDeploymentGroups", arg0, arg1)
	ret0, _ := ret[0].(*taskagent.GetDeploymentGroupsResponseValue)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDeploymentGroups indicates an expected call of GetDeploymentGroups.
func (mr *MockTaskAgentClientMockRecorder) GetDeploymentGroups(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDeploymentGroups", reflect.TypeOf((*MockTaskAgentClient)(nil).GetDeploymentGroups), arg0, arg1)
}

// GetDeploymentTarget mocks base method.
func (m *MockTaskAgentClient) GetDeploymentTarget(arg0 context.Context, arg1 taskagent.GetDeploymentTargetArgs) (*taskagent.DeploymentMachine, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDeploymentTarget", arg0, arg1)
	ret0, _ := ret[0].(*taskagent.DeploymentMachine)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDeploymentTarget indicates an expected call of GetDeploymentTarget.
func (mr *MockTaskAgentClientMockRecorder) GetDeploymentTarget(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDeploymentTarget", reflect.TypeOf((*MockTaskAgentClient)(nil).GetDeploymentTarget), arg0, arg1)
}

// GetDeploymentTargets mocks base method.
func (m *MockTaskAgentClient) GetDeploymentTargets(arg0 context.Context, arg1 taskagent.GetDeploymentTargetsArgs) (*taskagent.GetDeploymentTargetsResponseValue, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDeploymentTargets", arg0, arg1)
	ret0, _ := ret[0].(*taskagent.GetDeploymentTargetsResponseValue)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDeploymentTargets indicates an expected call of GetDeploymentTargets.
func (mr *MockTaskAgentClientMockRecorder) GetDeploymentTargets(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDeploymentTargets", reflect.TypeOf((*MockTaskAgentClient)(nil).GetDeploymentTargets), arg0, arg1)
}

// GetEnvironmentById mocks base method.
func (m *MockTaskAgentClient) GetEnvironmentById(arg0 context.Context, arg1 taskagent.GetEnvironmentByIdArgs) (*taskagent.EnvironmentInstance, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEnvironmentById", arg0, arg1)
	ret0, _ := ret[0].(*taskagent.EnvironmentInstance)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetEnvironmentById indicates an expected call of GetEnvironmentById.
func (mr *MockTaskAgentClientMockRecorder) GetEnvironmentById(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEnvironmentById", reflect.TypeOf((*MockTaskAgentClient)(nil).GetEnvironmentById), arg0, arg1)
}

// GetEnvironmentDeploymentExecutionRecords mocks base method.
func (m *MockTaskAgentClient) GetEnvironmentDeploymentExecutionRecords(arg0 context.Context, arg1 taskagent.GetEnvironmentDeploymentExecutionRecordsArgs) (*taskagent.GetEnvironmentDeploymentExecutionRecordsResponseValue, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEnvironmentDeploymentExecutionRecords", arg0, arg1)
	ret0, _ := ret[0].(*taskagent.GetEnvironmentDeploymentExecutionRecordsResponseValue)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetEnvironmentDeploymentExecutionRecords indicates an expected call of GetEnvironmentDeploymentExecutionRecords.
func (mr *MockTaskAgentClientMockRecorder) GetEnvironmentDeploymentExecutionRecords(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEnvironmentDeploymentExecutionRecords", reflect.TypeOf((*MockTaskAgentClient)(nil).GetEnvironmentDeploymentExecutionRecords), arg0, arg1)
}

// GetEnvironments mocks base method.
func (m *MockTaskAgentClient) GetEnvironments(arg0 context.Context, arg1 taskagent.GetEnvironmentsArgs) (*taskagent.GetEnvironmentsResponseValue, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEnvironments", arg0, arg1)
	ret0, _ := ret[0].(*taskagent.GetEnvironmentsResponseValue)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetEnvironments indicates an expected call of GetEnvironments.
func (mr *MockTaskAgentClientMockRecorder) GetEnvironments(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEnvironments", reflect.TypeOf((*MockTaskAgentClient)(nil).GetEnvironments), arg0, arg1)
}

// GetKubernetesResource mocks base method.
func (m *MockTaskAgentClient) GetKubernetesResource(arg0 context.Context, arg1 taskagent.GetKubernetesResourceArgs) (*taskagent.KubernetesResource, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetKubernetesResource", arg0, arg1)
	ret0, _ := ret[0].(*taskagent.KubernetesResource)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetKubernetesResource indicates an expected call of GetKubernetesResource.
func (mr *MockTaskAgentClientMockRecorder) GetKubernetesResource(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetKubernetesResource", reflect.TypeOf((*MockTaskAgentClient)(nil).GetKubernetesResource), arg0, arg1)
}

// GetTaskGroups mocks base method.
func (m *MockTaskAgentClient) GetTaskGroups(arg0 context.Context, arg1 taskagent.GetTaskGroupsArgs) (*[]taskagent.TaskGroup, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTaskGroups", arg0, arg1)
	ret0, _ := ret[0].(*[]taskagent.TaskGroup)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTaskGroups indicates an expected call of GetTaskGroups.
func (mr *MockTaskAgentClientMockRecorder) GetTaskGroups(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTaskGroups", reflect.TypeOf((*MockTaskAgentClient)(nil).GetTaskGroups), arg0, arg1)
}

// GetVariableGroup mocks base method.
func (m *MockTaskAgentClient) GetVariableGroup(arg0 context.Context, arg1 taskagent.GetVariableGroupArgs) (*taskagent.VariableGroup, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetVariableGroup", arg0, arg1)
	ret0, _ := ret[0].(*taskagent.VariableGroup)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetVariableGroup indicates an expected call of GetVariableGroup.
func (mr *MockTaskAgentClientMockRecorder) GetVariableGroup(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetVariableGroup", reflect.TypeOf((*MockTaskAgentClient)(nil).GetVariableGroup), arg0, arg1)
}

// GetVariableGroups mocks base method.
func (m *MockTaskAgentClient) GetVariableGroups(arg0 context.Context, arg1 taskagent.GetVariableGroupsArgs) (*[]taskagent.VariableGroup, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetVariableGroups", arg0, arg1)
	ret0, _ := ret[0].(*[]taskagent.VariableGroup)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetVariableGroups indicates an expected call of GetVariableGroups.
func (mr *MockTaskAgentClientMockRecorder) GetVariableGroups(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetVariableGroups", reflect.TypeOf((*MockTaskAgentClient)(nil).GetVariableGroups), arg0, arg1)
}

// GetVariableGroupsById mocks base method.
func (m *MockTaskAgentClient) GetVariableGroupsById(arg0 context.Context, arg1 taskagent.GetVariableGroupsByIdArgs) (*[]taskagent.VariableGroup, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetVariableGroupsById", arg0, arg1)
	ret0, _ := ret[0].(*[]taskagent.VariableGroup)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetVariableGroupsById indicates an expected call of GetVariableGroupsById.
func (mr *MockTaskAgentClientMockRecorder) GetVariableGroupsById(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetVariableGroupsById", reflect.TypeOf((*MockTaskAgentClient)(nil).GetVariableGroupsById), arg0, arg1)
}

// GetYamlSchema mocks base method.
func (m *MockTaskAgentClient) GetYamlSchema(arg0 context.Context, arg1 taskagent.GetYamlSchemaArgs) (any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetYamlSchema", arg0, arg1)
	ret0, _ := ret[0].(any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetYamlSchema indicates an expected call of GetYamlSchema.
func (mr *MockTaskAgentClientMockRecorder) GetYamlSchema(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetYamlSchema", reflect.TypeOf((*MockTaskAgentClient)(nil).GetYamlSchema), arg0, arg1)
}

// ReplaceAgent mocks base method.
func (m *MockTaskAgentClient) ReplaceAgent(arg0 context.Context, arg1 taskagent.ReplaceAgentArgs) (*taskagent.TaskAgent, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReplaceAgent", arg0, arg1)
	ret0, _ := ret[0].(*taskagent.TaskAgent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReplaceAgent indicates an expected call of ReplaceAgent.
func (mr *MockTaskAgentClientMockRecorder) ReplaceAgent(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReplaceAgent", reflect.TypeOf((*MockTaskAgentClient)(nil).ReplaceAgent), arg0, arg1)
}

// ShareVariableGroup mocks base method.
func (m *MockTaskAgentClient) ShareVariableGroup(arg0 context.Context, arg1 taskagent.ShareVariableGroupArgs) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ShareVariableGroup", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// ShareVariableGroup indicates an expected call of ShareVariableGroup.
func (mr *MockTaskAgentClientMockRecorder) ShareVariableGroup(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ShareVariableGroup", reflect.TypeOf((*MockTaskAgentClient)(nil).ShareVariableGroup), arg0, arg1)
}

// UpdateAgent mocks base method.
func (m *MockTaskAgentClient) UpdateAgent(arg0 context.Context, arg1 taskagent.UpdateAgentArgs) (*taskagent.TaskAgent, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateAgent", arg0, arg1)
	ret0, _ := ret[0].(*taskagent.TaskAgent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateAgent indicates an expected call of UpdateAgent.
func (mr *MockTaskAgentClientMockRecorder) UpdateAgent(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateAgent", reflect.TypeOf((*MockTaskAgentClient)(nil).UpdateAgent), arg0, arg1)
}

// UpdateAgentCloud mocks base method.
func (m *MockTaskAgentClient) UpdateAgentCloud(arg0 context.Context, arg1 taskagent.UpdateAgentCloudArgs) (*taskagent.TaskAgentCloud, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateAgentCloud", arg0, arg1)
	ret0, _ := ret[0].(*taskagent.TaskAgentCloud)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateAgentCloud indicates an expected call of UpdateAgentCloud.
func (mr *MockTaskAgentClientMockRecorder) UpdateAgentCloud(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateAgentCloud", reflect.TypeOf((*MockTaskAgentClient)(nil).UpdateAgentCloud), arg0, arg1)
}

// UpdateAgentPool mocks base method.
func (m *MockTaskAgentClient) UpdateAgentPool(arg0 context.Context, arg1 taskagent.UpdateAgentPoolArgs) (*taskagent.TaskAgentPool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateAgentPool", arg0, arg1)
	ret0, _ := ret[0].(*taskagent.TaskAgentPool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateAgentPool indicates an expected call of UpdateAgentPool.
func (mr *MockTaskAgentClientMockRecorder) UpdateAgentPool(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateAgentPool", reflect.TypeOf((*MockTaskAgentClient)(nil).UpdateAgentPool), arg0, arg1)
}

// UpdateDeploymentGroup mocks base method.
func (m *MockTaskAgentClient) UpdateDeploymentGroup(arg0 context.Context, arg1 taskagent.UpdateDeploymentGroupArgs) (*taskagent.DeploymentGroup, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateDeploymentGroup", arg0, arg1)
	ret0, _ := ret[0].(*taskagent.DeploymentGroup)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateDeploymentGroup indicates an expected call of UpdateDeploymentGroup.
func (mr *MockTaskAgentClientMockRecorder) UpdateDeploymentGroup(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateDeploymentGroup", reflect.TypeOf((*MockTaskAgentClient)(nil).UpdateDeploymentGroup), arg0, arg1)
}

// UpdateDeploymentTargets mocks base method.
func (m *MockTaskAgentClient) UpdateDeploymentTargets(arg0 context.Context, arg1 taskagent.UpdateDeploymentTargetsArgs) (*[]taskagent.DeploymentMachine, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateDeploymentTargets", arg0, arg1)
	ret0, _ := ret[0].(*[]taskagent.DeploymentMachine)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateDeploymentTargets indicates an expected call of UpdateDeploymentTargets.
func (mr *MockTaskAgentClientMockRecorder) UpdateDeploymentTargets(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateDeploymentTargets", reflect.TypeOf((*MockTaskAgentClient)(nil).UpdateDeploymentTargets), arg0, arg1)
}

// UpdateEnvironment mocks base method.
func (m *MockTaskAgentClient) UpdateEnvironment(arg0 context.Context, arg1 taskagent.UpdateEnvironmentArgs) (*taskagent.EnvironmentInstance, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateEnvironment", arg0, arg1)
	ret0, _ := ret[0].(*taskagent.EnvironmentInstance)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateEnvironment indicates an expected call of UpdateEnvironment.
func (mr *MockTaskAgentClientMockRecorder) UpdateEnvironment(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateEnvironment", reflect.TypeOf((*MockTaskAgentClient)(nil).UpdateEnvironment), arg0, arg1)
}

// UpdateTaskGroup mocks base method.
func (m *MockTaskAgentClient) UpdateTaskGroup(arg0 context.Context, arg1 taskagent.UpdateTaskGroupArgs) (*taskagent.TaskGroup, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateTaskGroup", arg0, arg1)
	ret0, _ := ret[0].(*taskagent.TaskGroup)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateTaskGroup indicates an expected call of UpdateTaskGroup.
func (mr *MockTaskAgentClientMockRecorder) UpdateTaskGroup(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateTaskGroup", reflect.TypeOf((*MockTaskAgentClient)(nil).UpdateTaskGroup), arg0, arg1)
}

// UpdateVariableGroup mocks base method.
func (m *MockTaskAgentClient) UpdateVariableGroup(arg0 context.Context, arg1 taskagent.UpdateVariableGroupArgs) (*taskagent.VariableGroup, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateVariableGroup", arg0, arg1)
	ret0, _ := ret[0].(*taskagent.VariableGroup)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateVariableGroup indicates an expected call of UpdateVariableGroup.
func (mr *MockTaskAgentClientMockRecorder) UpdateVariableGroup(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateVariableGroup", reflect.TypeOf((*MockTaskAgentClient)(nil).UpdateVariableGroup), arg0, arg1)
}
