// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/microsoft/azure-devops-go-api/azuredevops/v7/workitemtracking (interfaces: Client)
//
// Generated by this command:
//
//	mockgen -package=mocks -destination internal/mocks/workitemtracking_client_mock.go -mock_names Client=MockWorkItemTrackingClient github.com/microsoft/azure-devops-go-api/azuredevops/v7/workitemtracking Client
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	io "io"
	reflect "reflect"

	webapi "github.com/microsoft/azure-devops-go-api/azuredevops/v7/webapi"
	workitemtracking "github.com/microsoft/azure-devops-go-api/azuredevops/v7/workitemtracking"
	gomock "go.uber.org/mock/gomock"
)

// MockWorkItemTrackingClient is a mock of Client interface.
type MockWorkItemTrackingClient struct {
	ctrl     *gomock.Controller
	recorder *MockWorkItemTrackingClientMockRecorder
	isgomock struct{}
}

// MockWorkItemTrackingClientMockRecorder is the mock recorder for MockWorkItemTrackingClient.
type MockWorkItemTrackingClientMockRecorder struct {
	mock *MockWorkItemTrackingClient
}

// NewMockWorkItemTrackingClient creates a new mock instance.
func NewMockWorkItemTrackingClient(ctrl *gomock.Controller) *MockWorkItemTrackingClient {
	mock := &MockWorkItemTrackingClient{ctrl: ctrl}
	mock.recorder = &MockWorkItemTrackingClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWorkItemTrackingClient) EXPECT() *MockWorkItemTrackingClientMockRecorder {
	return m.recorder
}

// AddComment mocks base method.
func (m *MockWorkItemTrackingClient) AddComment(arg0 context.Context, arg1 workitemtracking.AddCommentArgs) (*workitemtracking.Comment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddComment", arg0, arg1)
	ret0, _ := ret[0].(*workitemtracking.Comment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddComment indicates an expected call of AddComment.
func (mr *MockWorkItemTrackingClientMockRecorder) AddComment(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddComment", reflect.TypeOf((*MockWorkItemTrackingClient)(nil).AddComment), arg0, arg1)
}

// AddWorkItemComment mocks base method.
func (m *MockWorkItemTrackingClient) AddWorkItemComment(arg0 context.Context, arg1 workitemtracking.AddWorkItemCommentArgs) (*workitemtracking.Comment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddWorkItemComment", arg0, arg1)
	ret0, _ := ret[0].(*workitemtracking.Comment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddWorkItemComment indicates an expected call of AddWorkItemComment.
func (mr *MockWorkItemTrackingClientMockRecorder) AddWorkItemComment(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddWorkItemComment", reflect.TypeOf((*MockWorkItemTrackingClient)(nil).AddWorkItemComment), arg0, arg1)
}

// CreateAttachment mocks base method.
func (m *MockWorkItemTrackingClient) CreateAttachment(arg0 context.Context, arg1 workitemtracking.CreateAttachmentArgs) (*workitemtracking.AttachmentReference, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateAttachment", arg0, arg1)
	ret0, _ := ret[0].(*workitemtracking.AttachmentReference)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateAttachment indicates an expected call of CreateAttachment.
func (mr *MockWorkItemTrackingClientMockRecorder) CreateAttachment(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateAttachment", reflect.TypeOf((*MockWorkItemTrackingClient)(nil).CreateAttachment), arg0, arg1)
}

// CreateCommentReaction mocks base method.
func (m *MockWorkItemTrackingClient) CreateCommentReaction(arg0 context.Context, arg1 workitemtracking.CreateCommentReactionArgs) (*workitemtracking.CommentReaction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateCommentReaction", arg0, arg1)
	ret0, _ := ret[0].(*workitemtracking.CommentReaction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateCommentReaction indicates an expected call of CreateCommentReaction.
func (mr *MockWorkItemTrackingClientMockRecorder) CreateCommentReaction(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateCommentReaction", reflect.TypeOf((*MockWorkItemTrackingClient)(nil).CreateCommentReaction), arg0, arg1)
}

// CreateOrUpdateClassificationNode mocks base method.
func (m *MockWorkItemTrackingClient) CreateOrUpdateClassificationNode(arg0 context.Context, arg1 workitemtracking.CreateOrUpdateClassificationNodeArgs) (*workitemtracking.WorkItemClassificationNode, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateOrUpdateClassificationNode", arg0, arg1)
	ret0, _ := ret[0].(*workitemtracking.WorkItemClassificationNode)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateOrUpdateClassificationNode indicates an expected call of CreateOrUpdateClassificationNode.
func (mr *MockWorkItemTrackingClientMockRecorder) CreateOrUpdateClassificationNode(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateOrUpdateClassificationNode", reflect.TypeOf((*MockWorkItemTrackingClient)(nil).CreateOrUpdateClassificationNode), arg0, arg1)
}

// CreateQuery mocks base method.
func (m *MockWorkItemTrackingClient) CreateQuery(arg0 context.Context, arg1 workitemtracking.CreateQueryArgs) (*workitemtracking.QueryHierarchyItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateQuery", arg0, arg1)
	ret0, _ := ret[0].(*workitemtracking.QueryHierarchyItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateQuery indicates an expected call of CreateQuery.
func (mr *MockWorkItemTrackingClientMockRecorder) CreateQuery(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateQuery", reflect.TypeOf((*MockWorkItemTrackingClient)(nil).CreateQuery), arg0, arg1)
}

// CreateTempQuery mocks base method.
func (m *MockWorkItemTrackingClient) CreateTempQuery(arg0 context.Context, arg1 workitemtracking.CreateTempQueryArgs) (*workitemtracking.TemporaryQueryResponseModel, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTempQuery", arg0, arg1)
	ret0, _ := ret[0].(*workitemtracking.TemporaryQueryResponseModel)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateTempQuery indicates an expected call of CreateTempQuery.
func (mr *MockWorkItemTrackingClientMockRecorder) CreateTempQuery(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTempQuery", reflect.TypeOf((*MockWorkItemTrackingClient)(nil).CreateTempQuery), arg0, arg1)
}

// CreateTemplate mocks base method.
func (m *MockWorkItemTrackingClient) CreateTemplate(arg0 context.Context, arg1 workitemtracking.CreateTemplateArgs) (*workitemtracking.WorkItemTemplate, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTemplate", arg0, arg1)
	ret0, _ := ret[0].(*workitemtracking.WorkItemTemplate)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateTemplate indicates an expected call of CreateTemplate.
func (mr *MockWorkItemTrackingClientMockRecorder) CreateTemplate(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTemplate", reflect.TypeOf((*MockWorkItemTrackingClient)(nil).CreateTemplate), arg0, arg1)
}

// CreateWorkItem mocks base method.
func (m *MockWorkItemTrackingClient) CreateWorkItem(arg0 context.Context, arg1 workitemtracking.CreateWorkItemArgs) (*workitemtracking.WorkItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateWorkItem", arg0, arg1)
	ret0, _ := ret[0].(*workitemtracking.WorkItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateWorkItem indicates an expected call of CreateWorkItem.
func (mr *MockWorkItemTrackingClientMockRecorder) CreateWorkItem(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateWorkItem", reflect.TypeOf((*MockWorkItemTrackingClient)(nil).CreateWorkItem), arg0, arg1)
}

// CreateWorkItemField mocks base method.
func (m *MockWorkItemTrackingClient) CreateWorkItemField(arg0 context.Context, arg1 workitemtracking.CreateWorkItemFieldArgs) (*workitemtracking.WorkItemField2, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateWorkItemField", arg0, arg1)
	ret0, _ := ret[0].(*workitemtracking.WorkItemField2)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateWorkItemField indicates an expected call of CreateWorkItemField.
func (mr *MockWorkItemTrackingClientMockRecorder) CreateWorkItemField(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateWorkItemField", reflect.TypeOf((*MockWorkItemTrackingClient)(nil).CreateWorkItemField), arg0, arg1)
}

// DeleteClassificationNode mocks base method.
func (m *MockWorkItemTrackingClient) DeleteClassificationNode(arg0 context.Context, arg1 workitemtracking.DeleteClassificationNodeArgs) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteClassificationNode", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteClassificationNode indicates an expected call of DeleteClassificationNode.
func (mr *MockWorkItemTrackingClientMockRecorder) DeleteClassificationNode(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteClassificationNode", reflect.TypeOf((*MockWorkItemTrackingClient)(nil).DeleteClassificationNode), arg0, arg1)
}

// DeleteComment mocks base method.
func (m *MockWorkItemTrackingClient) DeleteComment(arg0 context.Context, arg1 workitemtracking.DeleteCommentArgs) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteComment", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteComment indicates an expected call of DeleteComment.
func (mr *MockWorkItemTrackingClientMockRecorder) DeleteComment(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteComment", reflect.TypeOf((*MockWorkItemTrackingClient)(nil).DeleteComment), arg0, arg1)
}

// DeleteCommentReaction mocks base method.
func (m *MockWorkItemTrackingClient) DeleteCommentReaction(arg0 context.Context, arg1 workitemtracking.DeleteCommentReactionArgs) (*workitemtracking.CommentReaction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteCommentReaction", arg0, arg1)
	ret0, _ := ret[0].(*workitemtracking.CommentReaction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteCommentReaction indicates an expected call of DeleteCommentReaction.
func (mr *MockWorkItemTrackingClientMockRecorder) DeleteCommentReaction(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteCommentReaction", reflect.TypeOf((*MockWorkItemTrackingClient)(nil).DeleteCommentReaction), arg0, arg1)
}

// DeleteQuery mocks base method.
func (m *MockWorkItemTrackingClient) DeleteQuery(arg0 context.Context, arg1 workitemtracking.DeleteQueryArgs) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteQuery", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteQuery indicates an expected call of DeleteQuery.
func (mr *MockWorkItemTrackingClientMockRecorder) DeleteQuery(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteQuery", reflect.TypeOf((*MockWorkItemTrackingClient)(nil).DeleteQuery), arg0, arg1)
}

// DeleteTag mocks base method.
func (m *MockWorkItemTrackingClient) DeleteTag(arg0 context.Context, arg1 workitemtracking.DeleteTagArgs) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteTag", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteTag indicates an expected call of DeleteTag.
func (mr *MockWorkItemTrackingClientMockRecorder) DeleteTag(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteTag", reflect.TypeOf((*MockWorkItemTrackingClient)(nil).DeleteTag), arg0, arg1)
}

// DeleteTemplate mocks base method.
func (m *MockWorkItemTrackingClient) DeleteTemplate(arg0 context.Context, arg1 workitemtracking.DeleteTemplateArgs) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteTemplate", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteTemplate indicates an expected call of DeleteTemplate.
func (mr *MockWorkItemTrackingClientMockRecorder) DeleteTemplate(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteTemplate", reflect.TypeOf((*MockWorkItemTrackingClient)(nil).DeleteTemplate), arg0, arg1)
}

// DeleteWorkItem mocks base method.
func (m *MockWorkItemTrackingClient) DeleteWorkItem(arg0 context.Context, arg1 workitemtracking.DeleteWorkItemArgs) (*workitemtracking.WorkItemDelete, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteWorkItem", arg0, arg1)
	ret0, _ := ret[0].(*workitemtracking.WorkItemDelete)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteWorkItem indicates an expected call of DeleteWorkItem.
func (mr *MockWorkItemTrackingClientMockRecorder) DeleteWorkItem(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteWorkItem", reflect.TypeOf((*MockWorkItemTrackingClient)(nil).DeleteWorkItem), arg0, arg1)
}

// DeleteWorkItemField mocks base method.
func (m *MockWorkItemTrackingClient) DeleteWorkItemField(arg0 context.Context, arg1 workitemtracking.DeleteWorkItemFieldArgs) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteWorkItemField", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteWorkItemField indicates an expected call of DeleteWorkItemField.
func (mr *MockWorkItemTrackingClientMockRecorder) DeleteWorkItemField(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteWorkItemField", reflect.TypeOf((*MockWorkItemTrackingClient)(nil).DeleteWorkItemField), arg0, arg1)
}

// DeleteWorkItems mocks base method.
func (m *MockWorkItemTrackingClient) DeleteWorkItems(arg0 context.Context, arg1 workitemtracking.DeleteWorkItemsArgs) (*workitemtracking.WorkItemDeleteBatch, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteWorkItems", arg0, arg1)
	ret0, _ := ret[0].(*workitemtracking.WorkItemDeleteBatch)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteWorkItems indicates an expected call of DeleteWorkItems.
func (mr *MockWorkItemTrackingClientMockRecorder) DeleteWorkItems(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteWorkItems", reflect.TypeOf((*MockWorkItemTrackingClient)(nil).DeleteWorkItems), arg0, arg1)
}

// DestroyWorkItem mocks base method.
func (m *MockWorkItemTrackingClient) DestroyWorkItem(arg0 context.Context, arg1 workitemtracking.DestroyWorkItemArgs) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DestroyWorkItem", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// DestroyWorkItem indicates an expected call of DestroyWorkItem.
func (mr *MockWorkItemTrackingClientMockRecorder) DestroyWorkItem(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DestroyWorkItem", reflect.TypeOf((*MockWorkItemTrackingClient)(nil).DestroyWorkItem), arg0, arg1)
}

// GetAttachmentContent mocks base method.
func (m *MockWorkItemTrackingClient) GetAttachmentContent(arg0 context.Context, arg1 workitemtracking.GetAttachmentContentArgs) (io.ReadCloser, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAttachmentContent", arg0, arg1)
	ret0, _ := ret[0].(io.ReadCloser)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAttachmentContent indicates an expected call of GetAttachmentContent.
func (mr *MockWorkItemTrackingClientMockRecorder) GetAttachmentContent(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAttachmentContent", reflect.TypeOf((*MockWorkItemTrackingClient)(nil).GetAttachmentContent), arg0, arg1)
}

// GetAttachmentZip mocks base method.
func (m *MockWorkItemTrackingClient) GetAttachmentZip(arg0 context.Context, arg1 workitemtracking.GetAttachmentZipArgs) (io.ReadCloser, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAttachmentZip", arg0, arg1)
	ret0, _ := ret[0].(io.ReadCloser)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAttachmentZip indicates an expected call of GetAttachmentZip.
func (mr *MockWorkItemTrackingClientMockRecorder) GetAttachmentZip(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAttachmentZip", reflect.TypeOf((*MockWorkItemTrackingClient)(nil).GetAttachmentZip), arg0, arg1)
}

// GetClassificationNode mocks base method.
func (m *MockWorkItemTrackingClient) GetClassificationNode(arg0 context.Context, arg1 workitemtracking.GetClassificationNodeArgs) (*workitemtracking.WorkItemClassificationNode, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetClassificationNode", arg0, arg1)
	ret0, _ := ret[0].(*workitemtracking.WorkItemClassificationNode)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetClassificationNode indicates an expected call of GetClassificationNode.
func (mr *MockWorkItemTrackingClientMockRecorder) GetClassificationNode(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetClassificationNode", reflect.TypeOf((*MockWorkItemTrackingClient)(nil).GetClassificationNode), arg0, arg1)
}

// GetClassificationNodes mocks base method.
func (m *MockWorkItemTrackingClient) GetClassificationNodes(arg0 context.Context, arg1 workitemtracking.GetClassificationNodesArgs) (*[]workitemtracking.WorkItemClassificationNode, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetClassificationNodes", arg0, arg1)
	ret0, _ := ret[0].(*[]workitemtracking.WorkItemClassificationNode)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetClassificationNodes indicates an expected call of GetClassificationNodes.
func (mr *MockWorkItemTrackingClientMockRecorder) GetClassificationNodes(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetClassificationNodes", reflect.TypeOf((*MockWorkItemTrackingClient)(nil).GetClassificationNodes), arg0, arg1)
}

// GetComment mocks base method.
func (m *MockWorkItemTrackingClient) GetComment(arg0 context.Context, arg1 workitemtracking.GetCommentArgs) (*workitemtracking.Comment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetComment", arg0, arg1)
	ret0, _ := ret[0].(*workitemtracking.Comment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetComment indicates an expected call of GetComment.
func (mr *MockWorkItemTrackingClientMockRecorder) GetComment(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetComment", reflect.TypeOf((*MockWorkItemTrackingClient)(nil).GetComment), arg0, arg1)
}

// GetCommentReactions mocks base method.
func (m *MockWorkItemTrackingClient) GetCommentReactions(arg0 context.Context, arg1 workitemtracking.GetCommentReactionsArgs) (*[]workitemtracking.CommentReaction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCommentReactions", arg0, arg1)
	ret0, _ := ret[0].(*[]workitemtracking.CommentReaction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCommentReactions indicates an expected call of GetCommentReactions.
func (mr *MockWorkItemTrackingClientMockRecorder) GetCommentReactions(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCommentReactions", reflect.TypeOf((*MockWorkItemTrackingClient)(nil).GetCommentReactions), arg0, arg1)
}

// GetCommentVersion mocks base method.
func (m *MockWorkItemTrackingClient) GetCommentVersion(arg0 context.Context, arg1 workitemtracking.GetCommentVersionArgs) (*workitemtracking.CommentVersion, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCommentVersion", arg0, arg1)
	ret0, _ := ret[0].(*workitemtracking.CommentVersion)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCommentVersion indicates an expected call of GetCommentVersion.
func (mr *MockWorkItemTrackingClientMockRecorder) GetCommentVersion(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCommentVersion", reflect.TypeOf((*MockWorkItemTrackingClient)(nil).GetCommentVersion), arg0, arg1)
}

// GetCommentVersions mocks base method.
func (m *MockWorkItemTrackingClient) GetCommentVersions(arg0 context.Context, arg1 workitemtracking.GetCommentVersionsArgs) (*[]workitemtracking.CommentVersion, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCommentVersions", arg0, arg1)
	ret0, _ := ret[0].(*[]workitemtracking.CommentVersion)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCommentVersions indicates an expected call of GetCommentVersions.
func (mr *MockWorkItemTrackingClientMockRecorder) GetCommentVersions(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCommentVersions", reflect.TypeOf((*MockWorkItemTrackingClient)(nil).GetCommentVersions), arg0, arg1)
}

// GetComments mocks base method.
func (m *MockWorkItemTrackingClient) GetComments(arg0 context.Context, arg1 workitemtracking.GetCommentsArgs) (*workitemtracking.CommentList, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetComments", arg0, arg1)
	ret0, _ := ret[0].(*workitemtracking.CommentList)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetComments indicates an expected call of GetComments.
func (mr *MockWorkItemTrackingClientMockRecorder) GetComments(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetComments", reflect.TypeOf((*MockWorkItemTrackingClient)(nil).GetComments), arg0, arg1)
}

// GetCommentsBatch mocks base method.
func (m *MockWorkItemTrackingClient) GetCommentsBatch(arg0 context.Context, arg1 workitemtracking.GetCommentsBatchArgs) (*workitemtracking.CommentList, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCommentsBatch", arg0, arg1)
	ret0, _ := ret[0].(*workitemtracking.CommentList)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCommentsBatch indicates an expected call of GetCommentsBatch.
func (mr *MockWorkItemTrackingClientMockRecorder) GetCommentsBatch(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCommentsBatch", reflect.TypeOf((*MockWorkItemTrackingClient)(nil).GetCommentsBatch), arg0, arg1)
}

// GetDeletedWorkItem mocks base method.
func (m *MockWorkItemTrackingClient) GetDeletedWorkItem(arg0 context.Context, arg1 workitemtracking.GetDeletedWorkItemArgs) (*workitemtracking.WorkItemDelete, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDeletedWorkItem", arg0, arg1)
	ret0, _ := ret[0].(*workitemtracking.WorkItemDelete)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDeletedWorkItem indicates an expected call of GetDeletedWorkItem.
func (mr *MockWorkItemTrackingClientMockRecorder) GetDeletedWorkItem(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDeletedWorkItem", reflect.TypeOf((*MockWorkItemTrackingClient)(nil).GetDeletedWorkItem), arg0, arg1)
}

// GetDeletedWorkItemShallowReferences mocks base method.
func (m *MockWorkItemTrackingClient) GetDeletedWorkItemShallowReferences(arg0 context.Context, arg1 workitemtracking.GetDeletedWorkItemShallowReferencesArgs) (*[]workitemtracking.WorkItemDeleteShallowReference, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDeletedWorkItemShallowReferences", arg0, arg1)
	ret0, _ := ret[0].(*[]workitemtracking.WorkItemDeleteShallowReference)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDeletedWorkItemShallowReferences indicates an expected call of GetDeletedWorkItemShallowReferences.
func (mr *MockWorkItemTrackingClientMockRecorder) GetDeletedWorkItemShallowReferences(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDeletedWorkItemShallowReferences", reflect.TypeOf((*MockWorkItemTrackingClient)(nil).GetDeletedWorkItemShallowReferences), arg0, arg1)
}

// GetDeletedWorkItems mocks base method.
func (m *MockWorkItemTrackingClient) GetDeletedWorkItems(arg0 context.Context, arg1 workitemtracking.GetDeletedWorkItemsArgs) (*[]workitemtracking.WorkItemDeleteReference, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDeletedWorkItems", arg0, arg1)
	ret0, _ := ret[0].(*[]workitemtracking.WorkItemDeleteReference)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDeletedWorkItems indicates an expected call of GetDeletedWorkItems.
func (mr *MockWorkItemTrackingClientMockRecorder) GetDeletedWorkItems(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDeletedWorkItems", reflect.TypeOf((*MockWorkItemTrackingClient)(nil).GetDeletedWorkItems), arg0, arg1)
}

// GetEngagedUsers mocks base method.
func (m *MockWorkItemTrackingClient) GetEngagedUsers(arg0 context.Context, arg1 workitemtracking.GetEngagedUsersArgs) (*[]webapi.IdentityRef, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEngagedUsers", arg0, arg1)
	ret0, _ := ret[0].(*[]webapi.IdentityRef)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetEngagedUsers indicates an expected call of GetEngagedUsers.
func (mr *MockWorkItemTrackingClientMockRecorder) GetEngagedUsers(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEngagedUsers", reflect.TypeOf((*MockWorkItemTrackingClient)(nil).GetEngagedUsers), arg0, arg1)
}

// GetGithubConnectionRepositories mocks base method.
func (m *MockWorkItemTrackingClient) GetGithubConnectionRepositories(arg0 context.Context, arg1 workitemtracking.GetGithubConnectionRepositoriesArgs) (*[]workitemtracking.GitHubConnectionRepoModel, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetGithubConnectionRepositories", arg0, arg1)
	ret0, _ := ret[0].(*[]workitemtracking.GitHubConnectionRepoModel)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetGithubConnectionRepositories indicates an expected call of GetGithubConnectionRepositories.
func (mr *MockWorkItemTrackingClientMockRecorder) GetGithubConnectionRepositories(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetGithubConnectionRepositories", reflect.TypeOf((*MockWorkItemTrackingClient)(nil).GetGithubConnectionRepositories), arg0, arg1)
}

// GetGithubConnections mocks base method.
func (m *MockWorkItemTrackingClient) GetGithubConnections(arg0 context.Context, arg1 workitemtracking.GetGithubConnectionsArgs) (*[]workitemtracking.GitHubConnectionModel, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetGithubConnections", arg0, arg1)
	ret0, _ := ret[0].(*[]workitemtracking.GitHubConnectionModel)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetGithubConnections indicates an expected call of GetGithubConnections.
func (mr *MockWorkItemTrackingClientMockRecorder) GetGithubConnections(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetGithubConnections", reflect.TypeOf((*MockWorkItemTrackingClient)(nil).GetGithubConnections), arg0, arg1)
}

// GetQueries mocks base method.
func (m *MockWorkItemTrackingClient) GetQueries(arg0 context.Context, arg1 workitemtracking.GetQueriesArgs) (*[]workitemtracking.QueryHierarchyItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetQueries", arg0, arg1)
	ret0, _ := ret[0].(*[]workitemtracking.QueryHierarchyItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetQueries indicates an expected call of GetQueries.
func (mr *MockWorkItemTrackingClientMockRecorder) GetQueries(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetQueries", reflect.TypeOf((*MockWorkItemTrackingClient)(nil).GetQueries), arg0, arg1)
}

// GetQueriesBatch mocks base method.
func (m *MockWorkItemTrackingClient) GetQueriesBatch(arg0 context.Context, arg1 workitemtracking.GetQueriesBatchArgs) (*[]workitemtracking.QueryHierarchyItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetQueriesBatch", arg0, arg1)
	ret0, _ := ret[0].(*[]workitemtracking.QueryHierarchyItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetQueriesBatch indicates an expected call of GetQueriesBatch.
func (mr *MockWorkItemTrackingClientMockRecorder) GetQueriesBatch(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetQueriesBatch", reflect.TypeOf((*MockWorkItemTrackingClient)(nil).GetQueriesBatch), arg0, arg1)
}

// GetQuery mocks base method.
func (m *MockWorkItemTrackingClient) GetQuery(arg0 context.Context, arg1 workitemtracking.GetQueryArgs) (*workitemtracking.QueryHierarchyItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetQuery", arg0, arg1)
	ret0, _ := ret[0].(*workitemtracking.QueryHierarchyItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetQuery indicates an expected call of GetQuery.
func (mr *MockWorkItemTrackingClientMockRecorder) GetQuery(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetQuery", reflect.TypeOf((*MockWorkItemTrackingClient)(nil).GetQuery), arg0, arg1)
}

// GetQueryResultCount mocks base method.
func (m *MockWorkItemTrackingClient) GetQueryResultCount(arg0 context.Context, arg1 workitemtracking.GetQueryResultCountArgs) (*int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetQueryResultCount", arg0, arg1)
	ret0, _ := ret[0].(*int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetQueryResultCount indicates an expected call of GetQueryResultCount.
func (mr *MockWorkItemTrackingClientMockRecorder) GetQueryResultCount(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetQueryResultCount", reflect.TypeOf((*MockWorkItemTrackingClient)(nil).GetQueryResultCount), arg0, arg1)
}

// GetRecentActivityData mocks base method.
func (m *MockWorkItemTrackingClient) GetRecentActivityData(arg0 context.Context, arg1 workitemtracking.GetRecentActivityDataArgs) (*[]workitemtracking.AccountRecentActivityWorkItemModel2, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRecentActivityData", arg0, arg1)
	ret0, _ := ret[0].(*[]workitemtracking.AccountRecentActivityWorkItemModel2)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRecentActivityData indicates an expected call of GetRecentActivityData.
func (mr *MockWorkItemTrackingClientMockRecorder) GetRecentActivityData(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRecentActivityData", reflect.TypeOf((*MockWorkItemTrackingClient)(nil).GetRecentActivityData), arg0, arg1)
}

// GetRelationType mocks base method.
func (m *MockWorkItemTrackingClient) GetRelationType(arg0 context.Context, arg1 workitemtracking.GetRelationTypeArgs) (*workitemtracking.WorkItemRelationType, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRelationType", arg0, arg1)
	ret0, _ := ret[0].(*workitemtracking.WorkItemRelationType)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRelationType indicates an expected call of GetRelationType.
func (mr *MockWorkItemTrackingClientMockRecorder) GetRelationType(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRelationType", reflect.TypeOf((*MockWorkItemTrackingClient)(nil).GetRelationType), arg0, arg1)
}

// GetRelationTypes mocks base method.
func (m *MockWorkItemTrackingClient) GetRelationTypes(arg0 context.Context, arg1 workitemtracking.GetRelationTypesArgs) (*[]workitemtracking.WorkItemRelationType, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRelationTypes", arg0, arg1)
	ret0, _ := ret[0].(*[]workitemtracking.WorkItemRelationType)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRelationTypes indicates an expected call of GetRelationTypes.
func (mr *MockWorkItemTrackingClientMockRecorder) GetRelationTypes(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRelationTypes", reflect.TypeOf((*MockWorkItemTrackingClient)(nil).GetRelationTypes), arg0, arg1)
}

// GetReportingLinksByLinkType mocks base method.
func (m *MockWorkItemTrackingClient) GetReportingLinksByLinkType(arg0 context.Context, arg1 workitemtracking.GetReportingLinksByLinkTypeArgs) (*workitemtracking.ReportingWorkItemLinksBatch, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetReportingLinksByLinkType", arg0, arg1)
	ret0, _ := ret[0].(*workitemtracking.ReportingWorkItemLinksBatch)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetReportingLinksByLinkType indicates an expected call of GetReportingLinksByLinkType.
func (mr *MockWorkItemTrackingClientMockRecorder) GetReportingLinksByLinkType(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetReportingLinksByLinkType", reflect.TypeOf((*MockWorkItemTrackingClient)(nil).GetReportingLinksByLinkType), arg0, arg1)
}

// GetRevision mocks base method.
func (m *MockWorkItemTrackingClient) GetRevision(arg0 context.Context, arg1 workitemtracking.GetRevisionArgs) (*workitemtracking.WorkItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRevision", arg0, arg1)
	ret0, _ := ret[0].(*workitemtracking.WorkItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRevision indicates an expected call of GetRevision.
func (mr *MockWorkItemTrackingClientMockRecorder) GetRevision(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRevision", reflect.TypeOf((*MockWorkItemTrackingClient)(nil).GetRevision), arg0, arg1)
}

// GetRevisions mocks base method.
func (m *MockWorkItemTrackingClient) GetRevisions(arg0 context.Context, arg1 workitemtracking.GetRevisionsArgs) (*[]workitemtracking.WorkItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRevisions", arg0, arg1)
	ret0, _ := ret[0].(*[]workitemtracking.WorkItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRevisions indicates an expected call of GetRevisions.
func (mr *MockWorkItemTrackingClientMockRecorder) GetRevisions(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRevisions", reflect.TypeOf((*MockWorkItemTrackingClient)(nil).GetRevisions), arg0, arg1)
}

// GetRootNodes mocks base method.
func (m *MockWorkItemTrackingClient) GetRootNodes(arg0 context.Context, arg1 workitemtracking.GetRootNodesArgs) (*[]workitemtracking.WorkItemClassificationNode, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRootNodes", arg0, arg1)
	ret0, _ := ret[0].(*[]workitemtracking.WorkItemClassificationNode)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRootNodes indicates an expected call of GetRootNodes.
func (mr *MockWorkItemTrackingClientMockRecorder) GetRootNodes(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRootNodes", reflect.TypeOf((*MockWorkItemTrackingClient)(nil).GetRootNodes), arg0, arg1)
}

// GetTag mocks base method.
func (m *MockWorkItemTrackingClient) GetTag(arg0 context.Context, arg1 workitemtracking.GetTagArgs) (*workitemtracking.WorkItemTagDefinition, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTag", arg0, arg1)
	ret0, _ := ret[0].(*workitemtracking.WorkItemTagDefinition)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTag indicates an expected call of GetTag.
func (mr *MockWorkItemTrackingClientMockRecorder) GetTag(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTag", reflect.TypeOf((*MockWorkItemTrackingClient)(nil).GetTag), arg0, arg1)
}

// GetTags mocks base method.
func (m *MockWorkItemTrackingClient) GetTags(arg0 context.Context, arg1 workitemtracking.GetTagsArgs) (*[]workitemtracking.WorkItemTagDefinition, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTags", arg0, arg1)
	ret0, _ := ret[0].(*[]workitemtracking.WorkItemTagDefinition)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTags indicates an expected call of GetTags.
func (mr *MockWorkItemTrackingClientMockRecorder) GetTags(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTags", reflect.TypeOf((*MockWorkItemTrackingClient)(nil).GetTags), arg0, arg1)
}

// GetTemplate mocks base method.
func (m *MockWorkItemTrackingClient) GetTemplate(arg0 context.Context, arg1 workitemtracking.GetTemplateArgs) (*workitemtracking.WorkItemTemplate, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTemplate", arg0, arg1)
	ret0, _ := ret[0].(*workitemtracking.WorkItemTemplate)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTemplate indicates an expected call of GetTemplate.
func (mr *MockWorkItemTrackingClientMockRecorder) GetTemplate(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTemplate", reflect.TypeOf((*MockWorkItemTrackingClient)(nil).GetTemplate), arg0, arg1)
}

// GetTemplates mocks base method.
func (m *MockWorkItemTrackingClient) GetTemplates(arg0 context.Context, arg1 workitemtracking.GetTemplatesArgs) (*[]workitemtracking.WorkItemTemplateReference, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTemplates", arg0, arg1)
	ret0, _ := ret[0].(*[]workitemtracking.WorkItemTemplateReference)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTemplates indicates an expected call of GetTemplates.
func (mr *MockWorkItemTrackingClientMockRecorder) GetTemplates(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTemplates", reflect.TypeOf((*MockWorkItemTrackingClient)(nil).GetTemplates), arg0, arg1)
}

// GetUpdate mocks base method.
func (m *MockWorkItemTrackingClient) GetUpdate(arg0 context.Context, arg1 workitemtracking.GetUpdateArgs) (*workitemtracking.WorkItemUpdate, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUpdate", arg0, arg1)
	ret0, _ := ret[0].(*workitemtracking.WorkItemUpdate)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUpdate indicates an expected call of GetUpdate.
func (mr *MockWorkItemTrackingClientMockRecorder) GetUpdate(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUpdate", reflect.TypeOf((*MockWorkItemTrackingClient)(nil).GetUpdate), arg0, arg1)
}

// GetUpdates mocks base method.
func (m *MockWorkItemTrackingClient) GetUpdates(arg0 context.Context, arg1 workitemtracking.GetUpdatesArgs) (*[]workitemtracking.WorkItemUpdate, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUpdates", arg0, arg1)
	ret0, _ := ret[0].(*[]workitemtracking.WorkItemUpdate)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUpdates indicates an expected call of GetUpdates.
func (mr *MockWorkItemTrackingClientMockRecorder) GetUpdates(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUpdates", reflect.TypeOf((*MockWorkItemTrackingClient)(nil).GetUpdates), arg0, arg1)
}

// GetWorkArtifactLinkTypes mocks base method.
func (m *MockWorkItemTrackingClient) GetWorkArtifactLinkTypes(arg0 context.Context, arg1 workitemtracking.GetWorkArtifactLinkTypesArgs) (*[]workitemtracking.WorkArtifactLink, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWorkArtifactLinkTypes", arg0, arg1)
	ret0, _ := ret[0].(*[]workitemtracking.WorkArtifactLink)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetWorkArtifactLinkTypes indicates an expected call of GetWorkArtifactLinkTypes.
func (mr *MockWorkItemTrackingClientMockRecorder) GetWorkArtifactLinkTypes(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWorkArtifactLinkTypes", reflect.TypeOf((*MockWorkItemTrackingClient)(nil).GetWorkArtifactLinkTypes), arg0, arg1)
}

// GetWorkItem mocks base method.
func (m *MockWorkItemTrackingClient) GetWorkItem(arg0 context.Context, arg1 workitemtracking.GetWorkItemArgs) (*workitemtracking.WorkItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWorkItem", arg0, arg1)
	ret0, _ := ret[0].(*workitemtracking.WorkItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetWorkItem indicates an expected call of GetWorkItem.
func (mr *MockWorkItemTrackingClientMockRecorder) GetWorkItem(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWorkItem", reflect.TypeOf((*MockWorkItemTrackingClient)(nil).GetWorkItem), arg0, arg1)
}

// GetWorkItemField mocks base method.
func (m *MockWorkItemTrackingClient) GetWorkItemField(arg0 context.Context, arg1 workitemtracking.GetWorkItemFieldArgs) (*workitemtracking.WorkItemField2, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWorkItemField", arg0, arg1)
	ret0, _ := ret[0].(*workitemtracking.WorkItemField2)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetWorkItemField indicates an expected call of GetWorkItemField.
func (mr *MockWorkItemTrackingClientMockRecorder) GetWorkItemField(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWorkItemField", reflect.TypeOf((*MockWorkItemTrackingClient)(nil).GetWorkItemField), arg0, arg1)
}

// GetWorkItemFields mocks base method.
func (m *MockWorkItemTrackingClient) GetWorkItemFields(arg0 context.Context, arg1 workitemtracking.GetWorkItemFieldsArgs) (*[]workitemtracking.WorkItemField2, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWorkItemFields", arg0, arg1)
	ret0, _ := ret[0].(*[]workitemtracking.WorkItemField2)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetWorkItemFields indicates an expected call of GetWorkItemFields.
func (mr *MockWorkItemTrackingClientMockRecorder) GetWorkItemFields(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWorkItemFields", reflect.TypeOf((*MockWorkItemTrackingClient)(nil).GetWorkItemFields), arg0, arg1)
}

// GetWorkItemIconJson mocks base method.
func (m *MockWorkItemTrackingClient) GetWorkItemIconJson(arg0 context.Context, arg1 workitemtracking.GetWorkItemIconJsonArgs) (*workitemtracking.WorkItemIcon, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWorkItemIconJson", arg0, arg1)
	ret0, _ := ret[0].(*workitemtracking.WorkItemIcon)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetWorkItemIconJson indicates an expected call of GetWorkItemIconJson.
func (mr *MockWorkItemTrackingClientMockRecorder) GetWorkItemIconJson(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWorkItemIconJson", reflect.TypeOf((*MockWorkItemTrackingClient)(nil).GetWorkItemIconJson), arg0, arg1)
}

// GetWorkItemIconSvg mocks base method.
func (m *MockWorkItemTrackingClient) GetWorkItemIconSvg(arg0 context.Context, arg1 workitemtracking.GetWorkItemIconSvgArgs) (io.ReadCloser, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWorkItemIconSvg", arg0, arg1)
	ret0, _ := ret[0].(io.ReadCloser)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetWorkItemIconSvg indicates an expected call of GetWorkItemIconSvg.
func (mr *MockWorkItemTrackingClientMockRecorder) GetWorkItemIconSvg(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWorkItemIconSvg", reflect.TypeOf((*MockWorkItemTrackingClient)(nil).GetWorkItemIconSvg), arg0, arg1)
}

// GetWorkItemIconXaml mocks base method.
func (m *MockWorkItemTrackingClient) GetWorkItemIconXaml(arg0 context.Context, arg1 workitemtracking.GetWorkItemIconXamlArgs) (io.ReadCloser, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWorkItemIconXaml", arg0, arg1)
	ret0, _ := ret[0].(io.ReadCloser)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetWorkItemIconXaml indicates an expected call of GetWorkItemIconXaml.
func (mr *MockWorkItemTrackingClientMockRecorder) GetWorkItemIconXaml(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWorkItemIconXaml", reflect.TypeOf((*MockWorkItemTrackingClient)(nil).GetWorkItemIconXaml), arg0, arg1)
}

// GetWorkItemIcons mocks base method.
func (m *MockWorkItemTrackingClient) GetWorkItemIcons(arg0 context.Context, arg1 workitemtracking.GetWorkItemIconsArgs) (*[]workitemtracking.WorkItemIcon, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWorkItemIcons", arg0, arg1)
	ret0, _ := ret[0].(*[]workitemtracking.WorkItemIcon)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetWorkItemIcons indicates an expected call of GetWorkItemIcons.
func (mr *MockWorkItemTrackingClientMockRecorder) GetWorkItemIcons(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWorkItemIcons", reflect.TypeOf((*MockWorkItemTrackingClient)(nil).GetWorkItemIcons), arg0, arg1)
}

// GetWorkItemNextStatesOnCheckinAction mocks base method.
func (m *MockWorkItemTrackingClient) GetWorkItemNextStatesOnCheckinAction(arg0 context.Context, arg1 workitemtracking.GetWorkItemNextStatesOnCheckinActionArgs) (*[]workitemtracking.WorkItemNextStateOnTransition, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWorkItemNextStatesOnCheckinAction", arg0, arg1)
	ret0, _ := ret[0].(*[]workitemtracking.WorkItemNextStateOnTransition)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetWorkItemNextStatesOnCheckinAction indicates an expected call of GetWorkItemNextStatesOnCheckinAction.
func (mr *MockWorkItemTrackingClientMockRecorder) GetWorkItemNextStatesOnCheckinAction(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWorkItemNextStatesOnCheckinAction", reflect.TypeOf((*MockWorkItemTrackingClient)(nil).GetWorkItemNextStatesOnCheckinAction), arg0, arg1)
}

// GetWorkItemTemplate mocks base method.
func (m *MockWorkItemTrackingClient) GetWorkItemTemplate(arg0 context.Context, arg1 workitemtracking.GetWorkItemTemplateArgs) (*workitemtracking.WorkItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWorkItemTemplate", arg0, arg1)
	ret0, _ := ret[0].(*workitemtracking.WorkItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetWorkItemTemplate indicates an expected call of GetWorkItemTemplate.
func (mr *MockWorkItemTrackingClientMockRecorder) GetWorkItemTemplate(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWorkItemTemplate", reflect.TypeOf((*MockWorkItemTrackingClient)(nil).GetWorkItemTemplate), arg0, arg1)
}

// GetWorkItemType mocks base method.
func (m *MockWorkItemTrackingClient) GetWorkItemType(arg0 context.Context, arg1 workitemtracking.GetWorkItemTypeArgs) (*workitemtracking.WorkItemType, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWorkItemType", arg0, arg1)
	ret0, _ := ret[0].(*workitemtracking.WorkItemType)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetWorkItemType indicates an expected call of GetWorkItemType.
func (mr *MockWorkItemTrackingClientMockRecorder) GetWorkItemType(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWorkItemType", reflect.TypeOf((*MockWorkItemTrackingClient)(nil).GetWorkItemType), arg0, arg1)
}

// GetWorkItemTypeCategories mocks base method.
func (m *MockWorkItemTrackingClient) GetWorkItemTypeCategories(arg0 context.Context, arg1 workitemtracking.GetWorkItemTypeCategoriesArgs) (*[]workitemtracking.WorkItemTypeCategory, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWorkItemTypeCategories", arg0, arg1)
	ret0, _ := ret[0].(*[]workitemtracking.WorkItemTypeCategory)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetWorkItemTypeCategories indicates an expected call of GetWorkItemTypeCategories.
func (mr *MockWorkItemTrackingClientMockRecorder) GetWorkItemTypeCategories(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWorkItemTypeCategories", reflect.TypeOf((*MockWorkItemTrackingClient)(nil).GetWorkItemTypeCategories), arg0, arg1)
}

// GetWorkItemTypeCategory mocks base method.
func (m *MockWorkItemTrackingClient) GetWorkItemTypeCategory(arg0 context.Context, arg1 workitemtracking.GetWorkItemTypeCategoryArgs) (*workitemtracking.WorkItemTypeCategory, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWorkItemTypeCategory", arg0, arg1)
	ret0, _ := ret[0].(*workitemtracking.WorkItemTypeCategory)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetWorkItemTypeCategory indicates an expected call of GetWorkItemTypeCategory.
func (mr *MockWorkItemTrackingClientMockRecorder) GetWorkItemTypeCategory(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWorkItemTypeCategory", reflect.TypeOf((*MockWorkItemTrackingClient)(nil).GetWorkItemTypeCategory), arg0, arg1)
}

// GetWorkItemTypeFieldWithReferences mocks base method.
func (m *MockWorkItemTrackingClient) GetWorkItemTypeFieldWithReferences(arg0 context.Context, arg1 workitemtracking.GetWorkItemTypeFieldWithReferencesArgs) (*workitemtracking.WorkItemTypeFieldWithReferences, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWorkItemTypeFieldWithReferences", arg0, arg1)
	ret0, _ := ret[0].(*workitemtracking.WorkItemTypeFieldWithReferences)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetWorkItemTypeFieldWithReferences indicates an expected call of GetWorkItemTypeFieldWithReferences.
func (mr *MockWorkItemTrackingClientMockRecorder) GetWorkItemTypeFieldWithReferences(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWorkItemTypeFieldWithReferences", reflect.TypeOf((*MockWorkItemTrackingClient)(nil).GetWorkItemTypeFieldWithReferences), arg0, arg1)
}

// GetWorkItemTypeFieldsWithReferences mocks base method.
func (m *MockWorkItemTrackingClient) GetWorkItemTypeFieldsWithReferences(arg0 context.Context, arg1 workitemtracking.GetWorkItemTypeFieldsWithReferencesArgs) (*[]workitemtracking.WorkItemTypeFieldWithReferences, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWorkItemTypeFieldsWithReferences", arg0, arg1)
	ret0, _ := ret[0].(*[]workitemtracking.WorkItemTypeFieldWithReferences)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetWorkItemTypeFieldsWithReferences indicates an expected call of GetWorkItemTypeFieldsWithReferences.
func (mr *MockWorkItemTrackingClientMockRecorder) GetWorkItemTypeFieldsWithReferences(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWorkItemTypeFieldsWithReferences", reflect.TypeOf((*MockWorkItemTrackingClient)(nil).GetWorkItemTypeFieldsWithReferences), arg0, arg1)
}

// GetWorkItemTypeStates mocks base method.
func (m *MockWorkItemTrackingClient) GetWorkItemTypeStates(arg0 context.Context, arg1 workitemtracking.GetWorkItemTypeStatesArgs) (*[]workitemtracking.WorkItemStateColor, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWorkItemTypeStates", arg0, arg1)
	ret0, _ := ret[0].(*[]workitemtracking.WorkItemStateColor)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetWorkItemTypeStates indicates an expected call of GetWorkItemTypeStates.
func (mr *MockWorkItemTrackingClientMockRecorder) GetWorkItemTypeStates(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWorkItemTypeStates", reflect.TypeOf((*MockWorkItemTrackingClient)(nil).GetWorkItemTypeStates), arg0, arg1)
}

// GetWorkItemTypes mocks base method.
func (m *MockWorkItemTrackingClient) GetWorkItemTypes(arg0 context.Context, arg1 workitemtracking.GetWorkItemTypesArgs) (*[]workitemtracking.WorkItemType, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWorkItemTypes", arg0, arg1)
	ret0, _ := ret[0].(*[]workitemtracking.WorkItemType)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetWorkItemTypes indicates an expected call of GetWorkItemTypes.
func (mr *MockWorkItemTrackingClientMockRecorder) GetWorkItemTypes(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWorkItemTypes", reflect.TypeOf((*MockWorkItemTrackingClient)(nil).GetWorkItemTypes), arg0, arg1)
}

// GetWorkItems mocks base method.
func (m *MockWorkItemTrackingClient) GetWorkItems(arg0 context.Context, arg1 workitemtracking.GetWorkItemsArgs) (*[]workitemtracking.WorkItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWorkItems", arg0, arg1)
	ret0, _ := ret[0].(*[]workitemtracking.WorkItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetWorkItems indicates an expected call of GetWorkItems.
func (mr *MockWorkItemTrackingClientMockRecorder) GetWorkItems(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWorkItems", reflect.TypeOf((*MockWorkItemTrackingClient)(nil).GetWorkItems), arg0, arg1)
}

// GetWorkItemsBatch mocks base method.
func (m *MockWorkItemTrackingClient) GetWorkItemsBatch(arg0 context.Context, arg1 workitemtracking.GetWorkItemsBatchArgs) (*[]workitemtracking.WorkItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWorkItemsBatch", arg0, arg1)
	ret0, _ := ret[0].(*[]workitemtracking.WorkItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetWorkItemsBatch indicates an expected call of GetWorkItemsBatch.
func (mr *MockWorkItemTrackingClientMockRecorder) GetWorkItemsBatch(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWorkItemsBatch", reflect.TypeOf((*MockWorkItemTrackingClient)(nil).GetWorkItemsBatch), arg0, arg1)
}

// MigrateProjectsProcess mocks base method.
func (m *MockWorkItemTrackingClient) MigrateProjectsProcess(arg0 context.Context, arg1 workitemtracking.MigrateProjectsProcessArgs) (*workitemtracking.ProcessMigrationResultModel, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MigrateProjectsProcess", arg0, arg1)
	ret0, _ := ret[0].(*workitemtracking.ProcessMigrationResultModel)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// MigrateProjectsProcess indicates an expected call of MigrateProjectsProcess.
func (mr *MockWorkItemTrackingClientMockRecorder) MigrateProjectsProcess(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MigrateProjectsProcess", reflect.TypeOf((*MockWorkItemTrackingClient)(nil).MigrateProjectsProcess), arg0, arg1)
}

// QueryById mocks base method.
func (m *MockWorkItemTrackingClient) QueryById(arg0 context.Context, arg1 workitemtracking.QueryByIdArgs) (*workitemtracking.WorkItemQueryResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "QueryById", arg0, arg1)
	ret0, _ := ret[0].(*workitemtracking.WorkItemQueryResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// QueryById indicates an expected call of QueryById.
func (mr *MockWorkItemTrackingClientMockRecorder) QueryById(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "QueryById", reflect.TypeOf((*MockWorkItemTrackingClient)(nil).QueryById), arg0, arg1)
}

// QueryByWiql mocks base method.
func (m *MockWorkItemTrackingClient) QueryByWiql(arg0 context.Context, arg1 workitemtracking.QueryByWiqlArgs) (*workitemtracking.WorkItemQueryResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "QueryByWiql", arg0, arg1)
	ret0, _ := ret[0].(*workitemtracking.WorkItemQueryResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// QueryByWiql indicates an expected call of QueryByWiql.
func (mr *MockWorkItemTrackingClientMockRecorder) QueryByWiql(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "QueryByWiql", reflect.TypeOf((*MockWorkItemTrackingClient)(nil).QueryByWiql), arg0, arg1)
}

// QueryWorkItemsForArtifactUris mocks base method.
func (m *MockWorkItemTrackingClient) QueryWorkItemsForArtifactUris(arg0 context.Context, arg1 workitemtracking.QueryWorkItemsForArtifactUrisArgs) (*workitemtracking.ArtifactUriQueryResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "QueryWorkItemsForArtifactUris", arg0, arg1)
	ret0, _ := ret[0].(*workitemtracking.ArtifactUriQueryResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// QueryWorkItemsForArtifactUris indicates an expected call of QueryWorkItemsForArtifactUris.
func (mr *MockWorkItemTrackingClientMockRecorder) QueryWorkItemsForArtifactUris(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "QueryWorkItemsForArtifactUris", reflect.TypeOf((*MockWorkItemTrackingClient)(nil).QueryWorkItemsForArtifactUris), arg0, arg1)
}

// ReadReportingDiscussions mocks base method.
func (m *MockWorkItemTrackingClient) ReadReportingDiscussions(arg0 context.Context, arg1 workitemtracking.ReadReportingDiscussionsArgs) (*workitemtracking.ReportingWorkItemRevisionsBatch, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadReportingDiscussions", arg0, arg1)
	ret0, _ := ret[0].(*workitemtracking.ReportingWorkItemRevisionsBatch)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReadReportingDiscussions indicates an expected call of ReadReportingDiscussions.
func (mr *MockWorkItemTrackingClientMockRecorder) ReadReportingDiscussions(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadReportingDiscussions", reflect.TypeOf((*MockWorkItemTrackingClient)(nil).ReadReportingDiscussions), arg0, arg1)
}

// ReadReportingRevisionsGet mocks base method.
func (m *MockWorkItemTrackingClient) ReadReportingRevisionsGet(arg0 context.Context, arg1 workitemtracking.ReadReportingRevisionsGetArgs) (*workitemtracking.ReportingWorkItemRevisionsBatch, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadReportingRevisionsGet", arg0, arg1)
	ret0, _ := ret[0].(*workitemtracking.ReportingWorkItemRevisionsBatch)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReadReportingRevisionsGet indicates an expected call of ReadReportingRevisionsGet.
func (mr *MockWorkItemTrackingClientMockRecorder) ReadReportingRevisionsGet(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadReportingRevisionsGet", reflect.TypeOf((*MockWorkItemTrackingClient)(nil).ReadReportingRevisionsGet), arg0, arg1)
}

// ReadReportingRevisionsPost mocks base method.
func (m *MockWorkItemTrackingClient) ReadReportingRevisionsPost(arg0 context.Context, arg1 workitemtracking.ReadReportingRevisionsPostArgs) (*workitemtracking.ReportingWorkItemRevisionsBatch, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadReportingRevisionsPost", arg0, arg1)
	ret0, _ := ret[0].(*workitemtracking.ReportingWorkItemRevisionsBatch)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReadReportingRevisionsPost indicates an expected call of ReadReportingRevisionsPost.
func (mr *MockWorkItemTrackingClientMockRecorder) ReadReportingRevisionsPost(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadReportingRevisionsPost", reflect.TypeOf((*MockWorkItemTrackingClient)(nil).ReadReportingRevisionsPost), arg0, arg1)
}

// ReplaceTemplate mocks base method.
func (m *MockWorkItemTrackingClient) ReplaceTemplate(arg0 context.Context, arg1 workitemtracking.ReplaceTemplateArgs) (*workitemtracking.WorkItemTemplate, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReplaceTemplate", arg0, arg1)
	ret0, _ := ret[0].(*workitemtracking.WorkItemTemplate)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReplaceTemplate indicates an expected call of ReplaceTemplate.
func (mr *MockWorkItemTrackingClientMockRecorder) ReplaceTemplate(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReplaceTemplate", reflect.TypeOf((*MockWorkItemTrackingClient)(nil).ReplaceTemplate), arg0, arg1)
}

// RestoreWorkItem mocks base method.
func (m *MockWorkItemTrackingClient) RestoreWorkItem(arg0 context.Context, arg1 workitemtracking.RestoreWorkItemArgs) (*workitemtracking.WorkItemDelete, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RestoreWorkItem", arg0, arg1)
	ret0, _ := ret[0].(*workitemtracking.WorkItemDelete)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RestoreWorkItem indicates an expected call of RestoreWorkItem.
func (mr *MockWorkItemTrackingClientMockRecorder) RestoreWorkItem(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RestoreWorkItem", reflect.TypeOf((*MockWorkItemTrackingClient)(nil).RestoreWorkItem), arg0, arg1)
}

// SearchQueries mocks base method.
func (m *MockWorkItemTrackingClient) SearchQueries(arg0 context.Context, arg1 workitemtracking.SearchQueriesArgs) (*workitemtracking.QueryHierarchyItemsResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SearchQueries", arg0, arg1)
	ret0, _ := ret[0].(*workitemtracking.QueryHierarchyItemsResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SearchQueries indicates an expected call of SearchQueries.
func (mr *MockWorkItemTrackingClientMockRecorder) SearchQueries(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SearchQueries", reflect.TypeOf((*MockWorkItemTrackingClient)(nil).SearchQueries), arg0, arg1)
}

// SendMail mocks base method.
func (m *MockWorkItemTrackingClient) SendMail(arg0 context.Context, arg1 workitemtracking.SendMailArgs) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendMail", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendMail indicates an expected call of SendMail.
func (mr *MockWorkItemTrackingClientMockRecorder) SendMail(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendMail", reflect.TypeOf((*MockWorkItemTrackingClient)(nil).SendMail), arg0, arg1)
}

// UpdateClassificationNode mocks base method.
func (m *MockWorkItemTrackingClient) UpdateClassificationNode(arg0 context.Context, arg1 workitemtracking.UpdateClassificationNodeArgs) (*workitemtracking.WorkItemClassificationNode, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateClassificationNode", arg0, arg1)
	ret0, _ := ret[0].(*workitemtracking.WorkItemClassificationNode)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateClassificationNode indicates an expected call of UpdateClassificationNode.
func (mr *MockWorkItemTrackingClientMockRecorder) UpdateClassificationNode(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateClassificationNode", reflect.TypeOf((*MockWorkItemTrackingClient)(nil).UpdateClassificationNode), arg0, arg1)
}

// UpdateComment mocks base method.
func (m *MockWorkItemTrackingClient) UpdateComment(arg0 context.Context, arg1 workitemtracking.UpdateCommentArgs) (*workitemtracking.Comment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateComment", arg0, arg1)
	ret0, _ := ret[0].(*workitemtracking.Comment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateComment indicates an expected call of UpdateComment.
func (mr *MockWorkItemTrackingClientMockRecorder) UpdateComment(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateComment", reflect.TypeOf((*MockWorkItemTrackingClient)(nil).UpdateComment), arg0, arg1)
}

// UpdateGithubConnectionRepos mocks base method.
func (m *MockWorkItemTrackingClient) UpdateGithubConnectionRepos(arg0 context.Context, arg1 workitemtracking.UpdateGithubConnectionReposArgs) (*[]workitemtracking.GitHubConnectionRepoModel, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateGithubConnectionRepos", arg0, arg1)
	ret0, _ := ret[0].(*[]workitemtracking.GitHubConnectionRepoModel)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateGithubConnectionRepos indicates an expected call of UpdateGithubConnectionRepos.
func (mr *MockWorkItemTrackingClientMockRecorder) UpdateGithubConnectionRepos(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateGithubConnectionRepos", reflect.TypeOf((*MockWorkItemTrackingClient)(nil).UpdateGithubConnectionRepos), arg0, arg1)
}

// UpdateQuery mocks base method.
func (m *MockWorkItemTrackingClient) UpdateQuery(arg0 context.Context, arg1 workitemtracking.UpdateQueryArgs) (*workitemtracking.QueryHierarchyItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateQuery", arg0, arg1)
	ret0, _ := ret[0].(*workitemtracking.QueryHierarchyItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateQuery indicates an expected call of UpdateQuery.
func (mr *MockWorkItemTrackingClientMockRecorder) UpdateQuery(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateQuery", reflect.TypeOf((*MockWorkItemTrackingClient)(nil).UpdateQuery), arg0, arg1)
}

// UpdateTag mocks base method.
func (m *MockWorkItemTrackingClient) UpdateTag(arg0 context.Context, arg1 workitemtracking.UpdateTagArgs) (*workitemtracking.WorkItemTagDefinition, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateTag", arg0, arg1)
	ret0, _ := ret[0].(*workitemtracking.WorkItemTagDefinition)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateTag indicates an expected call of UpdateTag.
func (mr *MockWorkItemTrackingClientMockRecorder) UpdateTag(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateTag", reflect.TypeOf((*MockWorkItemTrackingClient)(nil).UpdateTag), arg0, arg1)
}

// UpdateWorkItem mocks base method.
func (m *MockWorkItemTrackingClient) UpdateWorkItem(arg0 context.Context, arg1 workitemtracking.UpdateWorkItemArgs) (*workitemtracking.WorkItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateWorkItem", arg0, arg1)
	ret0, _ := ret[0].(*workitemtracking.WorkItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateWorkItem indicates an expected call of UpdateWorkItem.
func (mr *MockWorkItemTrackingClientMockRecorder) UpdateWorkItem(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateWorkItem", reflect.TypeOf((*MockWorkItemTrackingClient)(nil).UpdateWorkItem), arg0, arg1)
}

// UpdateWorkItemComment mocks base method.
func (m *MockWorkItemTrackingClient) UpdateWorkItemComment(arg0 context.Context, arg1 workitemtracking.UpdateWorkItemCommentArgs) (*workitemtracking.Comment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateWorkItemComment", arg0, arg1)
	ret0, _ := ret[0].(*workitemtracking.Comment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateWorkItemComment indicates an expected call of UpdateWorkItemComment.
func (mr *MockWorkItemTrackingClientMockRecorder) UpdateWorkItemComment(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateWorkItemComment", reflect.TypeOf((*MockWorkItemTrackingClient)(nil).UpdateWorkItemComment), arg0, arg1)
}

// UpdateWorkItemField mocks base method.
func (m *MockWorkItemTrackingClient) UpdateWorkItemField(arg0 context.Context, arg1 workitemtracking.UpdateWorkItemFieldArgs) (*workitemtracking.WorkItemField2, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateWorkItemField", arg0, arg1)
	ret0, _ := ret[0].(*workitemtracking.WorkItemField2)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateWorkItemField indicates an expected call of UpdateWorkItemField.
func (mr *MockWorkItemTrackingClientMockRecorder) UpdateWorkItemField(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateWorkItemField", reflect.TypeOf((*MockWorkItemTrackingClient)(nil).UpdateWorkItemField), arg0, arg1)
}
