run:
  tests: true

output:
  print-issued-lines: false

linters:
  enable:
    - dupl
    - errcheck
    - errorlint
    - exhaustive
    - goconst
    - gocritic
    - gocyclo
    - gofmt
    - gofumpt
    - goimports
    - gosec
    - ineffassign
    - misspell
    - nilerr
    - paralleltest
    - revive
    - testifylint
    - unconvert
    - unparam
    - unused
    - vet
    - paralleltest
    - vetshadow

linters-settings:
  vet:
    check-shadowing: true
    use-installed-packages: true
  goconst:
    min-len: 8
    min-occurrences: 3
  gocyclo:
    min-complexity: 20
  gocritic:
    disabled-checks:
      - ifElseChain
  revive:
    rules:
      - name: exported
        disabled: true
      - name: package-comments
        disabled: true
  gofmt:
    rewrite-rules:
    - pattern:     'interface{}'
      replacement: 'any'
    - pattern:     'a[b:len(a)]'
      replacement: 'a[b:]'
  exhaustive:
    default-signifies-exhaustive: true

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude-use-default: false
  exclude:
    # Captured by errcheck.
    - "^(G104|G204):"
    # Very commonly not checked.
    - 'Error return value of .(.*\.Help|.*\.MarkFlagRequired|(os\.)?std(out|err)\..*|.*Close|.*Flush|os\.Remove(All)?|.*Print(f|ln|)|os\.(Un)?Setenv). is not checked'
