version: "2"
run:
  tests: false
linters:
  enable:
    - dupl
    - errorlint
    - exhaustive
    - goconst
    - gocritic
    #- gocyclo
    - gosec
    - misspell
    - nilerr
    - paralleltest
    - revive
    - testifylint
    - unconvert
    - unparam
  settings:
    exhaustive:
      default-signifies-exhaustive: true
    goconst:
      min-len: 8
      min-occurrences: 3
    gocritic:
      disabled-checks:
        - ifElseChain
    staticcheck:
      checks:
        - all
        - "-QF1008"
        - "-ST1000"
        - "-ST1003"
        - "-ST1016"
        - "-ST1020"
        - "-ST1021"
        - "-ST1000"
    gocyclo:
      min-complexity: 20
    revive:
      rules:
        - name: exported
          disabled: true
        - name: package-comments
          disabled: true
  exclusions:
    generated: lax
    rules:
      - path: (.+)\.go$
        text: '^(G104|G204):'
      - path: (.+)\.go$
        text: Error return value of .(.*\.Help|.*\.MarkFlagRequired|(os\.)?std(out|err)\..*|.*Close|.*Flush|os\.Remove(All)?|.*Print(f|ln)?|os\.(Un)?Setenv|fmt\.Fprint(f|ln)?). is not checked
    paths:
      - third_party$
      - builtin$
      - examples$
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
formatters:
  enable:
    - gofmt
    - gofumpt
    - goimports
  settings:
    gofmt:
      rewrite-rules:
        - pattern: interface{}
          replacement: any
        - pattern: a[b:len(a)]
          replacement: a[b:]
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
