# For more information on how to configure typos, see:
# - https://github.com/crate-ci/typos/blob/master/docs/reference.md
# - https://github.com/crate-ci/typos/blob/master/README.md#false-positives

[files]
# By default, typos will not check files that are ignored by git.
# You can override this behavior here.
# For example, to check all files, you would set:
# ignore-vcs = false
extend-exclude = [
  "**/.mise.toml",
  "vendor/**",
]

[default]
# This section contains the default configuration for all file types.
# You can override these settings for specific file types below.

# A list of words that should be considered correct.
# This is useful for words that are specific to your project.
# For example:
# extend-words = {
#   "myawesomeword" = "myawesomeword",
#   "another" = "another",
# }

# A list of regular expressions that should be ignored.
# This is useful for things like URLs, or other patterns that
# are not words.
# For example, to ignore all URLs:
# extend-ignore-re = [
#   "https?://[^`\\s]+",
# ]
extend-ignore-re = [
  # Ignore lines that end with `# spellchecker:disable-line` (or `//` in Go, `<!-- -->` in HTML/Markdown)
  "(?Rm)^.*(#|//|<!--)\\s*spellchecker:disable-line(\\s*-->)?$",
  # Ignore the line after `# spellchecker:ignore-next-line`
  "(#|//)\\s*spellchecker:ignore-next-line\\n.*",
  # Ignore blocks between `# spellchecker:off` and `# spellchecker:on`
  "(?s)(#|//)\\s*spellchecker:off.*?\\n\\s*(#|//)\\s*spellchecker:on",
  # Ignore the whole file starting from `# spellchecker:ignore-file` (top comment)
  "(?s)(#|//)\\s*spellchecker:ignore-file.*",
]
