package shared

var PullRequestFields = []string{
	"artifactId",
	"autoCompleteSetBy",
	"closedBy",
	"closedDate",
	"codeReviewId",
	"commits",
	"completionOptions",
	"completionQueueTime",
	"createdBy",
	"creationDate",
	"description",
	"forkSource",
	"hasMultipleMergeBases",
	"isDraft",
	"labels",
	"lastMergeCommit",
	"lastMergeSourceCommit",
	"lastMergeTargetCommit",
	"mergeFailureMessage",
	"mergeFailureType",
	"mergeId",
	"mergeOptions",
	"mergeStatus",
	"pullRequestId",
	"remoteUrl",
	"repository",
	"reviewers",
	"sourceRefName",
	"status",
	"supportsIterations",
	"targetRefName",
	"title",
	"url",
	"workItemRefs",
}
