# code: language=github-actions.workflows tabSize=2
---
name: Lint
on:
  push:
    tags-ignore:
      - v*
    paths:
      - .github/workflows/lint.yml
      - "**.go"
      - go.mod
      - go.sum
      - .golangci.yml

permissions:
  contents: read

env:
  LINT_VERSION: ${{ vars.golangci_version || '1.55.2' }}
  GO_VERSION: ${{ vars.golang_version || '1.20' }}

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Go ${{ env.GO_VERSION }}
        uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Check out code
        uses: actions/checkout@v3

      - name: Restore Go modules cache
        uses: actions/cache@v3
        with:
          path: ~/go/pkg/mod
          key: go-${{ runner.os }}-${{ hashFiles('go.mod') }}
          restore-keys: |
            go-${{ runner.os }}-

      - name: Verify dependencies
        run: |
          go mod verify
          go mod download

      - name: Run Lint checks
        uses: golangci/golangci-lint-action@v3
        with:
          version: v${{ env.LINT_VERSION }}
          install-mode: binary

      - name: Build docs generator
        run: |
          go build -o bin/gen-docs cmd/gen-docs/gen-docs.go || exit $?

      - name: Build gopfumpt
        run: |
          go install mvdan.cc/gofumpt@latest

      - name: Run checks
        run: |
          STATUS=0
          assert-nothing-changed() {
            local diff
            "$@" >/dev/null || return 1
            if ! diff="$(git diff -U1 --color --exit-code)"; then
              printf '\e[31mError: running `\e[1m%s\e[22m` results in modifications that you must check into version control:\e[0m\n%s\n\n' "$*" "$diff" >&2
              git checkout -- .
              STATUS=1
            fi
          }

          assert-nothing-changed ./bin/gen-docs --doc-path ./docs --website
          assert-nothing-changed gofumpt -l -w .
          assert-nothing-changed go mod tidy

          exit $STATUS
